### ISSUE TITLE
Pods view is being filtered by the namespace set in kubens

### ISSUE THREAD

**Issue by pdonovan** [aptakube/aptakube#100]
### Current and expected behavior

The Pods list seems to only show me pods from one namespace, not all namespaces like the screenshots show.

Further, if I run 'kubens another-namespace', expecting perhaps that the app would show that one, it still only shows pods from the original namespace I launched the app with. Switching the context in the top left of the app didn't change it, and neither does exiting the app and relaunching it. So at the moment I can only see pods from a single namespace.

I would expect the application to show all pods and resources on a cluster. I do not want to disable/remove kubens if at all possible as I've grown to rely on it for CLI tasks.

### Environment & Operating System

macOS 13.3
AKS 1.24.9
Aptakube 1.4.2

**Comment by goenning** [comment]
Hey @pdonovan, the very first time you open the app we show you pods from the namespace you have on your kubeconfig (which is what kubens sets).

After that, the app uses its own namespace selector and will no longer interface with your kubeconfig to get the namespace. So you can keep working with kubectl/kubens/etc without impact the app.

Pressing `CMD+N` opens the namespace selector (top right corner). You can switch to "All Namespaces" from this selector too, it's always the first option. So `CMD+N` + `Enter` will show you all namespaces.

Hope the above helps, but happy to clarify if you're still having issues with the app.

**Comment by pdonovan** [comment]
Thank you, that works!

I'm pretty sure that the filter box was blank until I first interacted with it? if it had said the initial namespace there I probably could have worked this out myself.
