### ISSUE TITLE
Incorrect units on memory resource

### ISSUE THREAD

**Issue by DanTulovsky** [aptakube/aptakube#102]
### Current and expected behavior

This is what the YAML display in aptakube shows:

![image](https://user-images.githubusercontent.com/509887/235758116-687a733a-2afd-4f2d-beba-5dbe654799c0.png)

And this is what the main container page shows:

![image](https://user-images.githubusercontent.com/509887/235758167-05dec5dc-732f-4ee5-af75-8f18c088d432.png)

Notice the `Gi` units on the main page.  Those should be `bytes`.

### Environment & Operating System

GKE.

**Comment by goenning** [comment]
Thanks @DanTulovsky I have a patch release scheduled for this and this fix will be included.

**Comment by goenning** [comment]
This should be fixed now with 1.4.3, but please reopen if it's not!
