### ISSUE TITLE
View ConfigMaps in the UI (from the pod/deployment view)

### ISSUE THREAD

**Issue by DanTulovsky** [aptakube/aptakube#103]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

One of the most useful features in lens is the ability to see the ConfigMap that is used by a pod (aptakube has this), click on it and view the contents (aptakube does not have this).

e.g.

![image](https://user-images.githubusercontent.com/509887/235984042-50b7b607-e776-4f28-bfc4-8f8a7f438204.png)

This is the Pod view. I can click on that blue link and be taken directly to the config to see it.

Please consider this for aptakube.  At least for me it's a blocker, since I use this functionality all the time.

**Comment by goenning** [comment]
Is that mounted as a volume?

We have a link when it's mounted as env variable:

![Screenshot 2023-05-03 at 18 00 26](https://user-images.githubusercontent.com/94755/235987634-8cafe568-6296-4074-a8b5-d0fb97bf27bc.png)

But it seems like I missed that on volume mounts

**Comment by goenning** [comment]
Thanks, will definitely add that link.

How urgent is this for you? I'll see if I can make this a patch release or if it'll wait for 1.5.0

**Comment by goenning** [comment]
Added on 1.4.4 :)

![image](https://github.com/aptakube/aptakube/assets/94755/e3c3e0df-0516-43af-9948-22525da5f363)
