### ISSUE TITLE
When editing yaml, formatting does not happen automatically (like in lens)

### ISSUE THREAD

**Issue by taivo123** [aptakube/aptakube#104]
### Current and expected behavior

for example if you split a long line by pressing enter, the tabulation does not happen automatically
![image](https://user-images.githubusercontent.com/85218884/237015368-84f571ee-d478-41f9-8183-e7ab34070513.png)

I am a paying customer, but no rush :)  

### Environment & Operating System

latest MacOS
EKS 1.20

**Comment by goenning** [comment]
Hey @taivo123 thanks for the bug report.

I'm struggling to reproduce this. I tried playing with long strings on both Aptakube and OpenLens, it seems like they both behave equally.

Would you mind recording a short video? 😅

**Comment by taivo123** [comment]
my bad, after updating things everything fits into one line and possibly there was no formatting issue in the first place 😊
