### ISSUE TITLE
log only shows 7d back

### ISSUE THREAD

**Issue by mschneider82** [aptakube/aptakube#106]
### Current and expected behavior

I have a long running application that logged the last line 3 weeks ago. I can only select last 7 days, so the log is always empty. 

A way to show "All" would be nice. (like lens)

### Environment & Operating System

ubuntu latest appimage

**Comment by goenning** [comment]
Added "All Logs" and "30d ago" in 1.4.4

**Comment by mschneider82** [comment]
All Logs is fine:

I can see the container starting log from 2022-12-12 15:56:55.808Z
and the last logged line from 2023-04-12 10:09:48.778Z
