### ISSUE TITLE
Missing  libssl.so.1.1

### ISSUE THREAD

**Issue by 14MR** [aptakube/aptakube#111]
### Current and expected behavior

I run Pop!_OS 22.04 LTS, after installing `aptakube_1.4.4_amd64.deb` aptakube doesn't start:
```
➜  ~ aptakube 
aptakube: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

The reason is, Pop!_OS 22.04 (and, probably, ubuntu itself) only has `libssl3.so` by default. 

Temporarily solution which worked for me: 
```
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb
```

### Environment & Operating System

```
➜  ~ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Comment by goenning** [comment]
Thanks @14MR i think this is a regression.

OpenSSL used to be bundled with the app, but was removed recently.  I'll either put it back or switch everything to Rustls
