### ISSUE TITLE
Command + P no longer searches CRDs

### ISSUE THREAD

**Issue by 24601** [aptakube/aptakube#115]
### Current and expected behavior

Hitting Command +P would search CRDs is what I would expect, it no longer does that. 

### Environment & Operating System

macOS ventura 13.4

k8s 1.24 (rancher)

**Comment by goenning** [comment]
Hi Basit!

The Cmd+P filter has been replaced by the Cmd+K command palette, should should take you faster to CRDs as well as any other built in resource.

In future versions this command palette will have even more shortcuts/actions.

Have a look and let me know how it goes
