### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by judavi** [aptakube/aptakube#116]
### Current and expected behavior

Hello folks!

I always get this message when I select one of my clusters. Strangely it works well when I do any kubectl command so I don't understand why not works with Apta

<img width="533" alt="image" src="https://github.com/aptakube/aptakube/assets/1766933/0801a435-9e2d-4cbe-83bb-cf6f77093f28">

### Environment & Operating System

MacOs Ventura 3.3.1 (a) 
Server Version: version.Info{Major:"1", Minor:"24"}

**Comment by judavi** [comment]
Adding insecure-skip-tls-verify: true in my kubeconfig fixed the issue

**Comment by goenning** [comment]
@judavi Thanks for the update. I would still like to find the root cause on why that error is thrown as that should not happen. 

Do you have a discord account? We could troubleshoot this issue together on [Aptakube Discord](https://discord.gg/FFp9bxHxtx)
