### ISSUE TITLE
Link from CRD Kind to matching Resources

### ISSUE THREAD

**Issue by metafeather** [aptakube/aptakube#119]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

I would find it very useful to be able to click on the value in the CRD `Kind` column and navigate to the matching Resource in the sidebar

**Comment by goenning** [comment]
I like this one, and it's an easy win.

It might be time for me to review the CRD screen as well, I currently simply print out the Spec / Status, but I can do better. 

I think I'll show the various versions, scope, stored version, acceptedNames, etc. 
For the openAPI schema, I'll probably build a tree like this one: https://aptakube.com/tools/spec-explorer/apps/v1/Deployment

You seem to be using CRD quite a bit, so if you have any suggestion on how to improve it please let know.

**Comment by goenning** [comment]
Theres a beta release on our discord with the link to resources + a redesigned CRD view in case you want to try before the official release 

https://discord.gg/FFp9bxHxtx

**Comment by goenning** [comment]
Shipped on 1.5
