### ISSUE TITLE
Select multiple namespaces

### ISSUE THREAD

**Issue by goenning** [aptakube/aptakube#12]
### What problem are you trying to solve?

Operating on “all namespaces” can be slow, but sometimes we need to look at objects from multiple namespaces and it’s cumbersome to do that currently on aptakube.

### Describe the solution you'd like

Just like we can select multiple contexts, we should be able to select multiple namespaces

**Comment by knippers** [comment]
I might be missing something but the latest Aptakube allows me to select multiple namespaces.

**Comment by nicholas-ochoa** [comment]
I mocked up a few screenshots to illustrate what I'd like to see for this feature:
<img width="2321" alt="current" src="https://github.com/aptakube/aptakube/assets/126299/71cf6252-bbbf-4b9c-b4c8-2f150a3bc8bb">
<img width="2321" alt="requested" src="https://github.com/aptakube/aptakube/assets/126299/85bbe161-2ba1-4fa5-9e6c-15b7332bf669">

**Comment by goenning** [comment]
I started working on multi-namespaces this week and I could use some feedback :)

Here's what I'm thinking:

1. If you click on the name (or `enter` key), it'll select only that namespace 
2. If you click on the checkbox (or `space` key), it'll toggle on/off that namespace

Here's a preview?

https://github.com/user-attachments/assets/1bfa93c9-1668-473e-9326-bb771350538e

**Comment by goenning** [comment]
This is now available on 1.7.4 🚀
