### ISSUE TITLE
Allow detailed / tabbed view to be opened into seperate windows...

### ISSUE THREAD

**Issue by projx** [aptakube/aptakube#122]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

The best feature of Lens, is its tabs, but they limit this to Shell and Logs... But it could do so much more, and be taken to the next level, by allowing each to put into seperate window, so they can all be shown on the screen at the same time.

Aptakube is already faster and smoother than Lens, but 1 limitation is, we can only work 1 view at a time... This could easily be addressed by allowing the Tabs (or what is shown in Overview, Logs, Yaml etc) to be opened into seperate windows

My favourite suggestion is on the right-click add "View item in seperate window" and "view logs in seperate window" options.  This I could have open the logs for Traefik and External-DNS...  or right-click on a Node, and it opens a separate window with a table showing all the Pods on that Node, with status, CPU, RAM etc..

Don't worry about multiple-panes in main window, this idea allows re-use of the existing layouts, but in seperate Windows..

I hope this makes sense..

**Comment by goenning** [comment]
There's support for multiple windows already, but I guess I need to make it more explicit.

You can open a new one with Cmd/Ctrl Shift N (I'm pretty sure it's this combination), or hold Cmd/Ctrl and click on any blue link.

Can you give it a try to see if that's what you're looking for?

**Comment by goenning** [comment]
Please reopen if I misunderstood your suggestion!
