### ISSUE TITLE
Probes View

### ISSUE THREAD

**Issue by filipevrevez** [aptakube/aptakube#123]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

It would be lovely to have the probes lists as we have for the ports.
Sometimes you may want to check how did we set probes and the delays without going to the yaml

**Comment by goenning** [comment]
I like this and it's an easy addition. I'll try to squeeze into 1.5 release which is due next week :)

**Comment by goenning** [comment]
I'll be on summer holidays 🏖️ for the next ~7 days, but I'll add this to the beta3 release which is going out today on [Discord](https://discord.com/invite/FFp9bxHxtx). So if you're interested in trying it out before the official release next week, please try the beta and share your feedback :)

Here's a sneak peek. Trying to make it as human-readable as possible.

![Screenshot 2023-07-03 at 11 16 52](https://github.com/aptakube/aptakube/assets/94755/d8e3d372-4069-4643-a4e0-791bbde8ebb8)

**Comment by goenning** [comment]
Shipped on 1.5
