### ISSUE TITLE
Sort the CRD List

### ISSUE THREAD

**Issue by DanTulovsky** [aptakube/aptakube#127]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Hi,

Can you please sort the CRD list on the left hand side?

![image](https://github.com/aptakube/aptakube/assets/509887/67b30d9e-8bf9-4ace-adbb-26211fdab748)

Thank you!

**Comment by matthewhembree** [comment]
Some type of sorted hierarchy would be nice. Maybe a tree view from the second-level domain name.

For me, I really would like a way to favorite/star the Group (maybe the Kind). Just to place the ones that I currently care about at the top of a list. Having a lot of CRDs just creates a wall of text.

Thanks!

**Comment by ilyavaiser** [comment]
Guys, this is annoying every time I use your app. Do the normal sorting, please.

**Comment by goenning** [comment]
I'm working on this at the moment, this is the current working version.

Better?

![image](https://github.com/user-attachments/assets/ea73f0a2-a3f7-4426-be06-cab4953f065d)

**Comment by goenning** [comment]
This is available on 1.7.0 now 🚀
