### ISSUE TITLE
<cmd>+k should find resources

### ISSUE THREAD

**Issue by DanTulovsky** [aptakube/aptakube#132]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

It would be super helpful if <cmd>+k would help me find actual resources (e.g. pods, deployments), not just take me to the sections available... Possibly filtering it first:

<cmd>+k
type: service <tab>
type: foo (results are filtered by service)

would take me to a service called foo.

Honestly this would be a killer feature.

thank you

**Comment by goenning** [comment]
Like this https://github.com/aptakube/aptakube/issues/81?

**Comment by goenning** [comment]
Thanks, will close this one!
