### ISSUE TITLE
Node Draining and Cordoning Capabilities within Nodes view

### ISSUE THREAD

**Issue by dibisis** [aptakube/aptakube#134]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

We're seeking to improve the process of managing node maintenance and pod eviction within our Kubernetes cluster. 

We propose adding functionality to the aptakube that allows for draining and cordoning of nodes. 
With this feature, we could improve the process of evicting pods safely and preparing the node for maintenance, directly from aptakube. This would help to streamline operations, reduce errors, and improve overall efficiency.

Thank you for your time and consideration, we look forward to hearing your thoughts on this proposed feature.

Best regards,
<img width="229" alt="image" src="https://github.com/aptakube/aptakube/assets/24780241/3c8ad7e8-8daf-47f8-abaf-b6230902814b">

**Comment by goenning** [comment]
Node Draining / Cordoning actions are coming (very) soon @dibisis and @khalid244

Video Demo:
https://github.com/aptakube/aptakube/assets/94755/0669e0d0-1f90-4e87-a6cf-115a65b36887

Available options (seems to be the most commonly used, but I'm open to feedback)!
![image](https://github.com/aptakube/aptakube/assets/94755/a57cb91a-28ea-40d8-a90b-0d02f31776f6)

**Comment by khalid244** [comment]
Great! I’ve been waiting for it. When do you think it will be ready? @goenning

**Comment by goenning** [comment]
It'll be released in about ~4 days
