### ISSUE TITLE
CRDs on GKE refreshing, making it hard to read the generated docs

### ISSUE THREAD

**Issue by oscar-b** [aptakube/aptakube#136]
### Current and expected behavior

Looking at a `HealthCheckPolicy` in a GKE cluster, `resourceVersion` updates regularly for no apparent reason. This causes the docs under `v1` to close all opened nodes (why not expand by default btw, not entirely clear that you need to click `object` to expand?).

### Environment & Operating System

GKE Autopilot cluster

**Comment by goenning** [comment]
Fixed on 1.5.1, but please reopen if the issue persists.

This feature was inspired on the spec explorer I built some time ago: https://aptakube.com/tools/spec-explorer
From my experience, if all nodes are automatically expanded, it gets really difficult to read
