### ISSUE TITLE
Command gets truncated in container view

### ISSUE THREAD

**Issue by DanTulovsky** [aptakube/aptakube#137]
### Current and expected behavior

Hi,

It looks like the command is truncated in the Container view when it reaches the end of the line:

![image](https://github.com/aptakube/aptakube/assets/509887/bde6f857-ddac-4587-ad2f-ac3207406b42)

It would be helpful if there was a way to see the entire command.

Thank you
dan

### Environment & Operating System

MacOS latest.  Aptakube 1.5.1

**Comment by goenning** [comment]
Should be fixed now on 1.5.2
