### ISSUE TITLE
Ui element bug in memory display

### ISSUE THREAD

**Issue by DanTulovsky** [aptakube/aptakube#139]
### Current and expected behavior

The memory bar starts too close to the number.  Please see picture below.

![image](https://github.com/aptakube/aptakube/assets/509887/7b9ea806-aa7b-43ce-bf56-62c9704210e0)

### Environment & Operating System

(Aptakube 1.5.1 on Debian)

**Comment by goenning** [comment]
Should be fixed now on 1.5.2
