### ISSUE TITLE
[Linux] Start a shell session on pods/nodes

### ISSUE THREAD

**Issue by goenning** [aptakube/aptakube#14]
### What problem are you trying to solve?

Nothing much to say, it’s a popular feature in Kubernetes that we should support

### Describe the solution you'd like

I’m considering wether we should simulate a terminal session inside aptakube or open a separate terminal window using the OS’s default terminal.

I’m inclined to open a separate terminal window given most users are familiar with their existing terminal setup. 

Open for feedback! Do you have any preference?

**Comment by paulmwatson** [comment]
Open separate terminal window please. I use k9s which has easy shell access built in but when running in Warp terminal on macOS k9s gets confused.

**Comment by goenning** [comment]
Version 1.0 adds support for gnome-terminal, with more to come in future!
