### ISSUE TITLE
Port name is cut off in the UI

### ISSUE THREAD

**Issue by DanTulovsky** [aptakube/aptakube#140]
### Current and expected behavior

Please see screenshot:

![image](https://github.com/aptakube/aptakube/assets/509887/58378097-3d25-4672-97fa-8cf7b475b914)

Perhaps it can have a tooltip that shows the full name?

thank you

### Environment & Operating System

Version 1.5.1 Debian.

**Comment by goenning** [comment]
Should be fixed now on 1.5.2
