### ISSUE TITLE
Memory request/limit not visible in UI if not string

### ISSUE THREAD

**Issue by DanTulovsky** [aptakube/aptakube#144]
### Current and expected behavior

Hi,

The following YAML:

![image](https://github.com/aptakube/aptakube/assets/509887/afe9ab45-480a-42f6-b15a-7028892621e4)

results in the following output in the container view:

![image](https://github.com/aptakube/aptakube/assets/509887/b08fd5a3-6850-46ee-8e2c-50847f38e609)

Possibly because the memory is not explicitly a string. It looks like this in the raw yaml file:

![image](https://github.com/aptakube/aptakube/assets/509887/9d0687e1-5294-4776-9afd-1c8139aa6bad)

(note that CPU has the same issue, but it looks ok)

Thank you
Dan

### Environment & Operating System

k8s:  1.25
aptakube: MacOS 1.5.3

**Comment by goenning** [comment]
Thanks, the issue was with the `k` suffix and It'll be fixed on 1.5.4. That particular limit will be shown as `8.79Gi`.

And just to confirm everything is ok with how the CPU is displayed?

**Comment by goenning** [comment]
Hi @DanTulovsky  this should be fixed on 1.5.4, but please reopen if it's not! Thanks
