### ISSUE TITLE
cpu/memory wrongly displayed

### ISSUE THREAD

**Issue by remmen-io** [aptakube/aptakube#148]
### Current and expected behavior

I have a k8s deployment with multiple pods.
The GUI shows cpu/memory limits identical to the ones defined in request.

YAML shows the difference

![CleanShot 2023-08-21 at 14 27 03](https://github.com/aptakube/aptakube/assets/118854388/f7f80f54-808d-48a0-9695-f91b77d80e2b)
![CleanShot 2023-08-21 at 14 26 50](https://github.com/aptakube/aptakube/assets/118854388/4be81e0b-4d5c-422c-9238-88ae97c118aa)

### Environment & Operating System

macOS 13.4.1
Kubernetes v1.23.16
Aptakube 1.5.4

**Comment by goenning** [comment]
Thanks for reporting this. I did some refactoring and this was a copy/paste mistake 🤦‍♂️

Fixed now on 1.5.5
