### ISSUE TITLE
v1.5.5 doesn't display certain custom resources, such as `Gateway`, `HTTPRoute` or `Kustomization`

### ISSUE THREAD

**Issue by oscar-b** [aptakube/aptakube#149]
### Current and expected behavior

Not sure when it began, but the latest version (v1.5.5) doesn't show anything when viewing `Gateway`, `HTTPRoute` or `GatewayClass` resources (under `gateway.networking.k8s.io`). It doesn't show `Kustomization` under `kustomize.toolkit.fluxcd.io` either.

### Environment & Operating System

macOS 13.2.1 (22D68)
Cluster is a GKE Autopilot v1.26.6-gke.1700

**Comment by goenning** [comment]
Thanks for reporting it. There were some changes on 1.5.4 in relation to CRD, so this is probably a regression. I'll look at it this week, for now reverting to 1.5.3 ( https://github.com/aptakube/aptakube/releases/tag/1.5.3 ) will probably fix it.

**Comment by goenning** [comment]
I was just trying this now and I was able to view gateways and httproutes.

What version of the CRD are you on? I'm using version `v0.7.1`.

I'll try flux and `Kustomization` next

![Screenshot 2023-08-22 at 17 54 42](https://github.com/aptakube/aptakube/assets/94755/0ca9159e-3fc7-4abf-b710-6e1cbac5dafa)

**Comment by goenning** [comment]
I forgot to ask, do you see a table with empty columns or you don't even see the table at all?

**Comment by goenning** [comment]
I may have found the reason, what’s your Safari version?

**Comment by oscar-b** [comment]
@goenning `Version 16.3 (18614.4.6.1.6)`

There was no table at all.

**Comment by goenning** [comment]
Thanks @oscar-b that confirmed my theory.

I just released 1.5.6 which should fix this, but please reopen if it's buggy.

**Comment by oscar-b** [comment]
@goenning Thanks, issue seems resolved in 1.5.6 👍🏻
