### ISSUE TITLE
Invalid number of failures for Jobs

### ISSUE THREAD

**Issue by DanTulovsky** [aptakube/aptakube#151]
### Current and expected behavior

Hi,

I don't know how this happened, but I am seeing the current picture under Jobs for a single job:

![image](https://github.com/aptakube/aptakube/assets/509887/b8d301d4-b99e-42c0-87fc-96efac9b062b)

Obviously you can't have 7 failures in 6 runs :)

### Environment & Operating System

Aptakube 1.5.5 on macOS

**Comment by goenning** [comment]
How does the status section of the YAML look like?

**Comment by goenning** [comment]
I had a look at the code and all it does is report what's in the YAML. This apparently means Kubernetes allowed it to run more than 6 times.
