### ISSUE TITLE
"Connection Error" when trying to view pods

### ISSUE THREAD

**Issue by gdubicki** [aptakube/aptakube#154]
### Current and expected behavior

Sometimes I get this error when trying to see a list of pods:
```
Connection Failure
Unable to connect due to errors below.

Connection Error
failed to perform initial object list: HyperError: error trying to
connect: tcp open error: Too many open files (os error 24)
```

<img width="486" alt="Screenshot 2023-09-06 at 18 30 51" src="https://github.com/aptakube/aptakube/assets/566632/23ef5f68-202f-4760-ad11-46d59861475e">

### Environment & Operating System

macOS 13.5.1 (22G90)
GKE 1.25.12-gke.500

**Comment by goenning** [comment]
That should happen if you have too many open files/connections, and it could be the result caused by multiple running apps/processes.

Can you check with lsof if most of these open files are coming from Aptakube?
