### ISSUE TITLE
Occasional slow updates and blocked filter box

### ISSUE THREAD

**Issue by DanTulovsky** [aptakube/aptakube#155]
### Current and expected behavior

Hi,

I somewhat often see:

![image](https://github.com/aptakube/aptakube/assets/509887/e51adb8d-2998-4f40-bbfb-eacf3627a345)

While it's updating, I can't type into the filter box.  My guess is that it's updating in the background, perhaps blocked on an API request?  Would it be possible to decouple the filter box from the updates?  usually I want to type something into it, but I can't and have to wait for it to do an update first.

There are other times when the UI is no longer responsive, presumably due to the size of the data.  In this case the view is filtered by namespace and you can see ~5k pods in there.

thank you!
dan

### Environment & Operating System

Linux; 1.5.9 aptakube.

**Comment by goenning** [comment]
The API requests always happens on the background, but the merge with the UI records happens on the main thread once the response is read. 

To be a bit more specific, once you view those 5k+ pods, they are stored in cache on the UI and when you move away from the pod list and go back to it, it'll only merge the difference between what's in cache and current state. 

If you view this list, move away and come back shortly after, do you still see this unresponsiveness?

**Comment by goenning** [comment]
Good news, I found a function the function that was taking 2~3sec on a 5k+ pods list.

Will be a lot faster on the next version (~10ms) :) 

Thanks for reporting this.

**Comment by goenning** [comment]
This should be fixed on 1.5.10, please reopen if it's not!
