### ISSUE TITLE
Incorrect Service Port Name

### ISSUE THREAD

**Issue by DanTulovsky** [aptakube/aptakube#156]
### Current and expected behavior

In the single Service view, it looks like when there are multiple ports defined for a service, the name of one of them is not correct.

Below, port `80` should be `httpinsecure`.

![image](https://github.com/aptakube/aptakube/assets/509887/50278ddb-e1bc-4cc0-b58c-2faa556d77db)

![image](https://github.com/aptakube/aptakube/assets/509887/c8b2684e-9680-4b6e-bcf6-7721470a7eaf)

Thank you

### Environment & Operating System

MacOS, AptaKube 1.5.9.

**Comment by goenning** [comment]
This should be fixed on 1.5.10, please reopen if it's not!
