### ISSUE TITLE
Ability to set the default selected namespace

### ISSUE THREAD

**Issue by GCook-anomix** [aptakube/aptakube#161]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

We rarely use the "default" namespace and every time I open the app I have to select "All namespaces" from the dropdown menu. It would be nice to choose which namespace is selected when the application starts up, including an option to open with "All namespaces" selected would be greatly appreciated.

**Comment by goenning** [comment]
That doesn’t look right. Aptakube should always preselect the previously used namespace, so if you change to “All”, the next time you close/open the app and select the same cluster, it should have “All” selected.

we only use the default namespace when you open the app for the first time.

Is this not the behaviour you’re seeing?

**Comment by GCook-anomix** [comment]
I stand corrected, you are right.
It seems it selects default only if it the first time I'm looking at a cluster.
Thank you and sorry for misunderstanding.
And great product, thank you for your hard work and dedication.
