### ISSUE TITLE
Edit yaml with extra window

### ISSUE THREAD

**Issue by mschneider82** [aptakube/aptakube#162]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

A second button for opening the YAML editor in an extra window would be nice. 

I often edit some deployments and when i have to search the cluster e.g. for an name of a configmap the yaml editor is closed and all changes i made are lost (a warning would be also good - in edit mode and a click in the cluster destroyes everything). It would be nice to edit it in an extra tab or window and keep the ability to browse the cluster and lookup some things.

**Comment by goenning** [comment]
If you Cmd+Click on Mac (or Ctrl+Click on Windows/Linux) on any of the menu items or even on the cluster, it'll open a new window. I think that'd help you as you can use the second window to navigate around while keeping the first window open for editing.

**Comment by mschneider82** [comment]
ok thanks that works! didnt know that shortcut. This helps alot.
