### ISSUE TITLE
Allow to select all contexts in initial screen with CMD+A

### ISSUE THREAD

**Issue by spr-mweber3** [aptakube/aptakube#163]
Basically what the title already said. It would be nice if, after startup when the first screen with the selection of contexts to connect to is displayed, it would be nice to be able to select all contexts quickly with CMD+A and press ENTER.

**Comment by spr-mweber3** [comment]
@goenning What do you think about that? In the meantime an additional idea has popped my mind. I think it would be very useful to define groups of contexts to be able to easily start up Aptakube with all contexts in a defined group. Currently I always need to select up to 30 contexts (in my case) one by one and connect to them.

**Comment by goenning** [comment]
@spr-mweber3 We have support for context groups in case you missed it: https://aptakube.com/docs/context-extension 

It's a bit of work to create the groups, but very useful afterwards.

---

I'm adding this shortcut to the next minor version (hopefully going out this week!). Cmd+A (or Ctrl+A) will select ALL contexts, but not the groups.

By the way, how's your experience using Aptakube with 30 contexts? Does it work well? I never tested it with that many contexts :)

**Comment by spr-mweber3** [comment]
Thanks for making me aware of that feature. I absolutely need to subscribe to the blog. Thanks for considering the implementation of my feature request. Really appreciated even though I now know about the context groups.

Regarding the experience with around 30 contexts. It's working just great. Nothing to complain about. We're running on EKS and Aptakube is blazingly fast.

Keep up the good work!
