### ISSUE TITLE
Cut off text in CRD

### ISSUE THREAD

**Issue by DanTulovsky** [aptakube/aptakube#166]
### Current and expected behavior

Would it be possible to make the text area wider?  

![image](https://github.com/aptakube/aptakube/assets/509887/fd700363-fa48-44b9-ab56-d81bb84bd112)

Thank you!

### Environment & Operating System

MacOS; Version 1.5.10

**Comment by goenning** [comment]
@DanTulovsky The new version has a new design for this view that expands full width. Let me know what you think!
