### ISSUE TITLE
Namespace selector navigation

### ISSUE THREAD

**Issue by filipevrevez** [aptakube/aptakube#168]
### Current and expected behavior

When scrolling with the keyboard on the namespace selector, the view doesn't change when you scroll to a line outside of view.
When scrolling with the mouse, you should always see the item that has focus

### Environment & Operating System

MacOs Ventura
Aptakube 1.5.10

**Comment by goenning** [comment]
@filipevrevez this should be fixed on the new version, but please reopen if it's not
