### ISSUE TITLE
Incorrect display of Stateful Sets

### ISSUE THREAD

**Issue by DanTulovsky** [aptakube/aptakube#170]
### Current and expected behavior

It looks like the StatefulSet display is not correct.  This is a list of StatefulSets (there are 1010 of them):

![SCR-20230926-rfp](https://github.com/aptakube/aptakube/assets/509887/22a8f3cd-1211-4875-9a85-9c7342686d5d)

Here I clicked into: spandb-shared-paid-dbset0-set9

![SCR-20230926-rfv](https://github.com/aptakube/aptakube/assets/509887/b71eb43c-f8bc-429b-be9f-a02df0490ad8)

It's showing me pods from all the stateful sets.  There should be exactly one pod here (in fact, you can see that in the heading).

Also, I realize this is a lot of data, but the application pauses for seconds at a time when dealing with it.  For example, I just clicked back arrow from the specific statefulset to the list, and there was a ~10 sec pause before I could interact with the ui.  Scrolling through the display (of 1010 stateful sets) is also painfully slow.

It doesn't matter which statefulset I click into it, I see a listing of all of them.  

Thank you
Dan

### Environment & Operating System

Debian Linux; aptakube 1.5.10.

**Comment by goenning** [comment]
How does the labelSelector of your StatefulSet look like?

**Comment by goenning** [comment]
Yes, it looks like a bug to me, I just need to understand what logic is used to select pods, it may be the label you mentioned, will investigate

**Comment by goenning** [comment]
There's a `currentRevision` and `updatedRevision` on the StatefulSet status field, and what's propagated to the Pods. So on the next version i'll combine the label selector + those to fields, which seems to work well!

**Comment by goenning** [comment]
@DanTulovsky this should be fixed on the new version, but please reopen if it's not
