### ISSUE TITLE
Helm Releases define displayed values

### ISSUE THREAD

**Issue by peteroneilljr** [aptakube/aptakube#184]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Under `Helm -> Release -> Overview` the values shown appear to be the chart values, not the current running values. This is a bit confusing because I would expect these values to be running on the cluster.

To add some clarity I think this section should show `User Values`. Received by running `helm get values release-name -n namespace` 

But having buttons at the bottom to show all values would be nice too.

`Get Default Values` : this would be `helm show values repository/chart`
`Get Running Values`: this would be `helm get values release-name -n namespace --all`

**Comment by goenning** [comment]
Hi Peter, thanks for the suggestion.

This was an oversight from my end when I first implemented it, the new version will show the user supplied values by default and a toggle to add the default values too (which is a merge of default + user values).

I think that should help right?

![Screenshot 2023-11-20 at 18 30 25](https://github.com/aptakube/aptakube/assets/94755/23184bcc-d14a-4c78-abc2-fdddf3595328)

**Comment by peteroneilljr** [comment]
Yup that should be great. Thanks!

**Comment by goenning** [comment]
hey @peteroneilljr have a look at the new version 1.6.0 and let me know what you think :)
I'm going to close for now, feel free to re-open if it's not what you was lookinng for
