### ISSUE TITLE
Missing limits

### ISSUE THREAD

**Issue by vojtechvelkjop** [aptakube/aptakube#185]
### Current and expected behavior

We have correctly set memory/cpu request/limits but in the pods overview, we see a message: "missing limit" on memory/cpu but directly in the container overview it correctly shows graphs according to memory limits.

<img width="200" alt="Screenshot 2023-11-21 at 11 31 16" src="https://github.com/aptakube/aptakube/assets/89193391/a96abf40-7580-411a-9332-9ec543dc6030">
<img width="237" alt="Screenshot 2023-11-21 at 11 31 25" src="https://github.com/aptakube/aptakube/assets/89193391/448b5502-7364-4334-a0ce-e86d99e00bc7">

It can be related due to linkerd injection. 

### Environment & Operating System

macOS sonoma
aks: v1.26.6

**Comment by goenning** [comment]
Does the linkerd container have limits? If it doesn't, then we can't calculate the limits for the pod.

**Comment by vojtechvelkjop** [comment]
Yes container has limit defined in the deployment.
<img width="847" alt="Screenshot 2023-11-23 at 9 33 05" src="https://github.com/aptakube/aptakube/assets/89193391/1dfd4874-0f2c-484d-9619-284c3fae634b">
<img width="971" alt="Screenshot 2023-11-23 at 9 33 30" src="https://github.com/aptakube/aptakube/assets/89193391/ce17b53d-4a96-45d2-ac48-55151cf12c9b">

**Comment by vojtechvelkjop** [comment]
yes you are right. 
so that mean that pod showing sum of limits all containers in the pod. hmm
Thinking in theoreticaly if linkerd was almost on 100% of memory/cpu and second container very low so we will see average value. 
but it is not related with fault bug. 
Thanks you and closing.

**Comment by vojtechvelkjop** [comment]
second container was without a limit.
