### ISSUE TITLE
Sort the environment variables by key name

### ISSUE THREAD

**Issue by nicholas-ochoa** [aptakube/aptakube#186]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Can an option (or even default) be added to sort the environment variable list alphabetically? Right now it's sorted the same way it's defined in the yaml, but that can make it hard to spot environment variables at a glance without scanning through the whole list

<img width="77" alt="image" src="https://github.com/aptakube/aptakube/assets/126299/b985898f-7111-459c-a738-b569c268f4a2">

**Comment by nicholas-ochoa** [comment]
Any chance this will get implemented? Seems like an easy usability win.

**Comment by goenning** [comment]
Hi @nicholas-ochoa this should be fixed on 1.6.3, want to give it a try? Please reopen if it's still not working

**Comment by nicholas-ochoa** [comment]
That looks fantastic! Thank you!
