### ISSUE TITLE
Aptakube 1.6.0 crashes when setting up Terminated Logs in Linux

### ISSUE THREAD

**Issue by joseluisq** [aptakube/aptakube#190]
### Current and expected behavior

Recently I updated from 1.5.12 to 1.6.0 but when I go to My Cluster > Deployments > My Deployment X > Logs and set the logs to display "Logs From Terminated". Then it crashes the next time that I open again the same interface section.

CPU increases rapidly as well as RAM as a result the Log window gets frozen and crashes afterwards.

Mention that I'm using the latest Debian 12.2 Bookworm and I wanted to look at the logs of my crashed pod at that time.

I did fallback to the previous 1.5.12 and works as expected.

If you need more details please let me know.

Best!
Jose

### Environment & Operating System

Debian 12.2 Bookworm x86_64
Linux Kernel 6.1.0-13-amd64
Kubernetes EKS: v1.23.17-eks - linux/amd64

**Comment by joseluisq** [comment]
This occurs probably also because I have a lot of log entries and 1.6.0 can not handle them all properly but 1.5.12 does it. 

BTW I guess a pagination or similar functionality could help there.

**Comment by goenning** [comment]
If you look at a pod that have fewer logs, does it also crash?

I’ve updated the terminal emulator I use on aptakube, but I might need to revert if this is happening frequently

**Comment by goenning** [comment]
@joseluisq this should be fixed now on 1.6.1, but please reopen if it's not. Thanks for reporting this bug!

**Comment by joseluisq** [comment]
@goenning I just tested it and now it works as expected.
