### ISSUE TITLE
Unnessary space when display crd spec/status

### ISSUE THREAD

**Issue by zzjin** [aptakube/aptakube#193]
### Current and expected behavior

After upgrade to 1.6.0, there has long spaces at crd's spec and status.
Witch means when showing some short spec with long status, the page is not shown info as effective as much.

![image](https://github.com/aptakube/aptakube/assets/679757/8c36a4f3-3e98-4935-85f2-ae5da4ea72c4)

The empty spaces eat almost all screens.

### Environment & Operating System

Any kubernetes cluster when shown cert-manager's Cert crd.

**Comment by goenning** [comment]
@zzjin have a look at version 1.6.1, it should be in a much better state now. Let me know what you think.
