### ISSUE TITLE
Add Cordon and Drain

### ISSUE THREAD

**Issue by khalid244** [aptakube/aptakube#195]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

I’ve been using Lens for some time before switching to Aptakube. While I’ve had a great experience with Aptakube’s user interface, I do miss some features from Lens. For instance, when I right-click on a node in Lens, options for `Cordon` and `Drain` appear. This is really convenient as it saves me from having to write code.

**Comment by goenning** [comment]
Hey @khalid244 thanks for the suggestion. 

We're already tracking this feature here https://github.com/aptakube/aptakube/issues/134 It's actually the current most wanted issue, so that'll definitely be the next feature to be implemented :)
