### ISSUE TITLE
No contexts available

### ISSUE THREAD

**Issue by victor-teles** [aptakube/aptakube#20]
### Current and expected behavior

Apkutabe is showing empty state screen "No contexts" but kubectl config get-contexts works fine.

### Additional context

![image](https://user-images.githubusercontent.com/78874691/201386226-41926ce7-8f5e-4f60-a50b-b6da63b27b89.png)

![image](https://user-images.githubusercontent.com/78874691/201386281-9c24a0bf-7e2f-421c-bebb-b261872ea513.png)

### Operating System

macOS monterey

### Environment

clientVersion:
  buildDate: "2022-11-09T13:36:36Z"
  compiler: gc
  gitCommit: 872a965c6c6526caa949f0c6ac028ef7aff3fb78
  gitTreeState: clean
  gitVersion: v1.25.4
  goVersion: go1.19.3
  major: "1"
  minor: "25"
  platform: darwin/arm64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-09-16T05:12:30Z"
  compiler: gc
  gitCommit: 5a00aa04b05c45ce3367463825613527f91f86df
  gitTreeState: clean
  gitVersion: v1.23.5
  goVersion: go1.17.8
  major: "1"
  minor: "23"
  platform: linux/amd64

WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1

**Comment by goenning** [comment]
hey Victor, thanks for the report.

It's an interesting one, do you have any special setup for your contexts? Or are they all in your `$HOME/.kube/config`?

If you could run these as well: `kubectl config get-contexts -v=9` and also `echo $KUBECONFIG`

**Comment by victor-teles** [comment]
@goenning hi, they are all in `~/.kube/config`


### output of `kubectl config get-contexts -v=9`
![image](https://user-images.githubusercontent.com/78874691/201389367-83b2694f-db3f-4f56-9453-db4af8c392a5.png)

### output of `echo $KUBECONFIG`

![image](https://user-images.githubusercontent.com/78874691/201389468-5a2763bd-58cd-4f6b-a781-07294122d14a.png)

**Comment by goenning** [comment]
Thanks, that's seems all ok.

I believe Aptakube is failing due to a parsing an error. Aptakube uses kube-rs as the Kubernetes client and its kubeconfig parser is a bit more strict than client-go's used in kubectl.

If you'd like to help me on this, I'd suggest temporarily removing some content of your kubeconfig file until you find what property is causing this. If I were to take a guess, I'd say it's probably somewhere on the `users`, if you have any.

In parallel, I'll do 2 things:

1. Update Aptakube to display parsing errors, if any
2. Try and get kube-rs to use the same parsing model as client-go

**Comment by goenning** [comment]
Hey @victor-teles 

I have a beta version of 0.8.0 that'll give us more information when that happens, could you please try this on [Aptakube-0.8.0-beta.app.zip](https://github.com/aptakube/aptakube/files/9994863/Aptakube.app.zip)?

Thanks!

**Comment by victor-teles** [comment]
@goenning 

Hope it helps 

<img width="890" alt="image" src="https://user-images.githubusercontent.com/78874691/201791305-9c86ddc7-497d-4327-9cef-c51379700973.png">

**Comment by goenning** [comment]
Aptakube 0.8.0 was released today and there's a few improvements around parsing kubeconfig that should resolve this. Please feel free to reopen if it's still not working!
