### ISSUE TITLE
Helm list showing app as deployed, but helm list shows real status

### ISSUE THREAD

**Issue by jwhitcraft** [aptakube/aptakube#202]
### Current and expected behavior

When looking at a helm resource on the list page, it was showing as deployed

<img width="1034" alt="image" src="https://github.com/aptakube/aptakube/assets/26738/2baa3ec2-13cc-4b02-a03c-53dd9d156389">

but when looking at the resource with `helm list` it was showing as `pending-upgrade`

<img width="1524" alt="image" src="https://github.com/aptakube/aptakube/assets/26738/edc58acb-a7b4-414d-b92e-fdbf34622004">

### Environment & Operating System

MacOS 14.2.1 (M2 Max)

**Comment by goenning** [comment]
I'm going to logoff soon, but before I go, what I first noticed that aptakube is showing revision 5 while helm is showing revision 6 (age differs too). 

Are these actually the same cluster? The releases in other namespaces are matching OK?

**Comment by jwhitcraft** [comment]
@goenning yes, they were, i forgot to get the screen of of aptakube before i did the helm rollback in the console.  I can check one of my other clusters and see if i can find the same issue.

**Comment by goenning** [comment]
@jwhitcraft i have a fix for it, just finishing up some other small things first and then I’ll release it. Either tomorrow or on Monday!

**Comment by goenning** [comment]
Hi @jwhitcraft this should be fixed on 1.6.3, want to give it a try? Please reopen if it's still not working
