### ISSUE TITLE
Unexpected `switch-context` multi-select behaviour

### ISSUE THREAD

**Issue by Mikhail5555** [aptakube/aptakube#203]
### Current and expected behavior

When using the `Switch Context` command, and going to the main screen
![image](https://github.com/aptakube/aptakube/assets/7824786/f2dfd917-d07c-40a6-a9bb-622fae6be3c1)
#### Expected Behavior:
selecting an entry and then clicking Enter I would expect to only have that single cluster selected/connected.

#### Current Behavior:
But as the behaviour got changed in 1.6.2, it now adds the selected cluster to the "mutli cluster" feature, requiring manually deselecting all old clusters with space (which makes switching between two clusters pretty annoying.)

Also I don't see any mention of it in the changelog, so could it be it was an accidental change?

### Environment & Operating System

macOS 13.6.3
aptakube: 1.6.2

Kubectl:
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.0

**Comment by goenning** [comment]
It’s on the “improvements” section of the changelog

the intention was to make it faster to re-connect to previous clusters, but I can see how that’s annoying when switching clusters.

for now, you can press ESC and it’ll clear the selection, but I’ll review this for the next minor release. 

Do you think the previous behaviour was better?
What if the preselection only happened when the launches?

**Comment by goenning** [comment]
Hi @Mikhail5555 I reverted this feature on 1.6.3 until I find a better way of doing it.
