### ISSUE TITLE
Add a possibility to delete multiple resources at once.

### ISSUE THREAD

**Issue by didukh86** [aptakube/aptakube#204]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Hello, thanks for the excellent product! It would be great to have a possibility to mark multiple resources (pods, deployments for example)  using a checkbox and delete them at once.

**Comment by goenning** [comment]
Hi @didukh86 thanks for the suggestion. Can you upvote this one instead ? That issue is a duplicate and has a lot more votes already

https://github.com/aptakube/aptakube/issues/55

**Comment by didukh86** [comment]
Thank you for the response
