### ISSUE TITLE
Spec and status of Pod Disruption Budget can't be seen

### ISSUE THREAD

**Issue by oscar-b** [aptakube/aptakube#207]
### Current and expected behavior

Can't see anything in these text fields since they're quite small

<img width="1258" alt="image" src="https://github.com/aptakube/aptakube/assets/85102/f9033bac-b8b8-49ce-a532-dea6150b23ce">

### Environment & Operating System

macOS 14.1.1 (23B81)

**Comment by goenning** [comment]
Hi @oscar-b this should be fixed on 1.6.3, want to give it a try? Please reopen if it's still not working

**Comment by oscar-b** [comment]
@goenning Looks like it's fixed, yes! 👍🏻
