### ISSUE TITLE
Non existent pods being shown on statefulsets and deployments

### ISSUE THREAD

**Issue by tgigli** [aptakube/aptakube#208]
### Current and expected behavior

When I click in a deployment or statefulset, I see, in one example, 2 pods of MongoDB (appsmith-mongodb-2). One is real and the other one is not. I'm currently connected to only one cluster. 
![image](https://github.com/aptakube/aptakube/assets/2750335/47025949-a2f6-4677-9f2c-90a02c017711)
The red one is the pod that doesn't exist.
The same here:
![image](https://github.com/aptakube/aptakube/assets/2750335/857ad697-6ede-4b72-a54f-647d961336e9)
When I click in the nonexistent pod, it shows that the pod doesn't exist and then, when I go back to the statefulset, it shows me the correct information (without the nonexistent pod).

### Environment & Operating System

Ubuntu 22.04.4 LTS
EKS 1.25

**Comment by goenning** [comment]
If you restart the app, do those pods come back again on the list?

**Comment by tgigli** [comment]
I haven't tried this yet. However, if I click on the nonexistent pod and then click the back arrow, it vanishes.
This doesn't happen all the time. I've also noticed that the nonexistent pod is also scheduled on a nonexistent node. So, it's possible that this is either old data (I used to leave the app open for days) or mixed data from other clusters. However, I haven't been able to confirm that yet.

**Comment by tgigli** [comment]
It just happened again. I was working in a specific namespace and then I ran a helm delete command (in the command line). Then I redeployed the chart using terraform (cli too) and then I went back to see the statefulsets. This image shows duplications.
![image](https://github.com/aptakube/aptakube/assets/2750335/5e9ef9e4-0475-4c41-8a34-04cc86332033)

**Comment by goenning** [comment]
Question about this second time you reproduced it: was the app open for a while before this happened?

I'll keep trying to reproduce it, but in case you find a way to reproduce it consistently please let me know, that'd help a lot!

**Comment by goenning** [comment]
I believe this issue was fixed in 1.6.8, however I was never able to reproduce it initially, so I'm not 100% sure. I'll keep this issue open for a few more days, so please report back if you see it again when using the latest version.

**Comment by mboutet** [comment]
Just had the issue while having the pods view opened while a rolling update of a statefulset was occuring on v1.6.9.

**Comment by goenning** [comment]
Thanks helpful, thanks. I’ll give it a try with a statefulset too. Which update strategy does that SS has?

**Comment by mboutet** [comment]
It's using the default upgrade strategy (I didn't set it explicitely) and it's using the Parallel podManagementPolicy if that matters.

**Comment by goenning** [comment]
Seems like it's fixed? Please reopen if that happens again
