### ISSUE TITLE
Node Search Filter Based on Taint Key/Value

### ISSUE THREAD

**Issue by midaslmg94** [aptakube/aptakube#209]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Current Behavior:
When searching for nodes with a specific taint (e.g., nodeType:monitoring) in the cluster, the current search functionality appears to be limited to node names or other straightforward identifiers. This limitation becomes evident when using tools like Aptakube or OpenLens, where, for example, a search in Aptakube yields no results, whereas OpenLens might return two nodes without explicitly considering the taint key/value pairs.

> In aptakube
- <img width="1562" alt="image" src="https://github.com/aptakube/aptakube/assets/37613051/5a6595f4-4d0c-4582-80ed-7aa7973e1ca4">

> In OpenLens
- <img width="1200" alt="image" src="https://github.com/aptakube/aptakube/assets/37613051/1ff71d9b-a77f-41e7-b027-3ee461215297">

Suggested Enhancement:
I propose the addition of a node search filter that allows users to query based on the key/value pairs of taints. This enhancement would significantly improve the user experience by providing a more granular and targeted search capability, especially in environments with complex taint and toleration setups.

**Comment by iammoen** [comment]
Not quite the same issue as the above but annotations and labels aren't searchable either.

**Comment by goenning** [comment]
@midaslmg94 this was released on [1.6.5](https://github.com/aptakube/aptakube/releases/tag/1.6.5) but I forgot to update this issue! I'll close it for now, but please reopen if it's not working.
