### ISSUE TITLE
 port-forwarding pod issue. aptakube (Version 1.6.2 (20240130.193024)) 

### ISSUE THREAD

**Issue by Franck-Yannick** [aptakube/aptakube#210]
### Current and expected behavior

Current behavior: when we do the of the pod via aptakube we get the following error:
.......
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
........
![Screenshot 2024-02-23 at 1 14 12 PM](https://github.com/aptakube/aptakube/assets/33133903/4099c536-892c-4e89-908d-be8c9dbb0c5d)

Expected behavior: We expect a response from the pod as shown on the screenshot below:
......
default api healthcheck
......
![Screenshot 2024-02-23 at 1 02 50 PM](https://github.com/aptakube/aptakube/assets/33133903/6715af89-9167-44d1-bb33-8943d0f3ef7a)

Using aptakube (Version 1.6.2 (20240130.193024)) 

### Environment & Operating System

MacOS Ventura 13.0

**Comment by goenning** [comment]
It seems like port forward worked because that first error message is coming from the pod

if you navigate to `http://localhost:59297/healthcheck`, does it work?

**Comment by Franck-Yannick** [comment]
thanks for the update @goenning
