### ISSUE TITLE
Feat: select multiple objects

### ISSUE THREAD

**Issue by A1994SC** [aptakube/aptakube#211]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

I need to clean out some resource, e.i. pods/jobs, and at the moment I have to do the following per object that I want get ride of:
- right click on the object
- click delete
- the click delete on the pop-up window

It isn't too bad for say 2-3 pods, but if I wanted to delete 5+ it is just very time consuming to do it via aptakube... 

I know I can go down to `kubectl` but would be nice to stay inside the aptakube window

**Comment by goenning** [comment]
That’s the current most request feature and something I’ll add to the next release, stay tuned :)

I’ll close this one in favour of the original request https://github.com/aptakube/aptakube/issues/55

**Comment by A1994SC** [comment]
Ah, tried to search for it, but failed! Thanks I will track that one
