### ISSUE TITLE
Search for CRD kinds

### ISSUE THREAD

**Issue by mochja** [aptakube/aptakube#219]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

I usually don't remember under which `apiVersion` my resource (Kind) is located. `Super + P` could open a dialog with fuzzy search for the Custom Resource (and maybe not only), where I type `Canary` and upon pressing enter I would get navigated to the `flagger.app/Canary` view.

Lighter version of this feature could provide a filter input above the Cluster option in the left sidebar, to filter out the items in the sidebar menu.

**Comment by goenning** [comment]
Hi @mochja , have you tried `CMD + K` (or CTRL if Windows/Linux)? Seems be what you're looking for

**Comment by mochja** [comment]
@goenning thank you, exactly what I was looking for :)
