### ISSUE TITLE
Add a column on the `Nodes` tab for the taint value. 

### ISSUE THREAD

**Issue by engrkenjitanaka** [aptakube/aptakube#224]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Having visibility to what node groups are having issues with a quick glance would be really helpful. Taint `key` is shown, but if you're using a naming structure like `component=x-service`, `component=y-service` it's not that helpful.

![Screenshot 2024-04-25 at 14 26 37](https://github.com/aptakube/aptakube/assets/75548949/4dda1608-0be9-4566-947c-b44a9619de36)

**Comment by goenning** [comment]
I added the taint value to the same column, should be available now on 1.6.5 :)
