### ISSUE TITLE
Getting `Stream closed: EOF` after a few minutes of having the `Logs` tab opened

### ISSUE THREAD

**Issue by mboutet** [aptakube/aptakube#236]
### Current and expected behavior

It seems like the log stream closes after a few minutes for containers not outputting any new logs. The issue doesn't seem present for containers outputting logs often (at least a couple of time per minute).

My colleague with the same hardware and version as me also experiences the same issue.

Thank you!

### Environment & Operating System

Apple M2 Max
macOS 13.6.2 (22G320
Aptakube Version 1.6.6 (20240509.095758)
K8s v1.27.3

**Comment by goenning** [comment]
Thanks for reporting this @mboutet I was able to reproduce this and I have a fix lined up for 1.6.7, which should go out next week 🤞

**Comment by goenning** [comment]
This should be fixed on 1.6.7, but let me know if it's not!
