### ISSUE TITLE
Force reload window

### ISSUE THREAD

**Issue by jobace78** [aptakube/aptakube#237]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Hi,

Sometimes when rolling out a deployment or a statefulset POD's are "duplicated". I have to switch to another window and come back to refresh.

Could a "force" refresh be implemented (e.g. cmd + r)?

Thanks.

**Comment by mboutet** [comment]
Possibly related to https://github.com/aptakube/aptakube/issues/208 maybe? We've also had this issue with duplicate pods showing up sometimes. As @jobace78 pointed out, the current workaround is to switch to another view and come back to the previous view. Personally, I think fixing the underlying cause of that issue would be better than a force reload.

**Comment by jobace78** [comment]
Sure, but if not in this scenario, maybe another one in the future may require this "forceful" approach.

**Comment by goenning** [comment]
Yeah that seems like a bug which I definitely want to fix first before thinking of adding a refresh button.

is this happening to you as well @mboutet ?
Have any of you been able to reproduce it consistently?

**Comment by mboutet** [comment]
@goenning, yes a colleague and I had the issue a few times. I don't have a systematic way to reproduce it at the moment, but it does seem to occur, as pointed out by OP, when rolling out or scaling in/out a deployment/statefulset.

I can't say for sure, but I would say it mostly occurs when the rollout/scale in/scale out starts when Aptakube is not visible (different space on macOS) or out of focus and then I come back to it and notice the duplicate pods.

**Comment by goenning** [comment]
I'll close this one in favour of #208 

but as mention on the other issue, I believe this is fixed now, but not 100% sure it.
