### ISSUE TITLE
Optional ConfigMap when not existing prevents environment variables from being showed

### ISSUE THREAD

**Issue by medbayoudh** [aptakube/aptakube#239]
### Current and expected behavior

Optional ConfigMaps when they do not exist are causing error in showing the environment variables. 
I have 3 environments, in one it was set -> environment variables are loaded and showed correctly. 
In the others when the configMap was not there, all environment variables are not shown. 
When I access the pod and run `printenv` the environment variables they get printed.

<img width="224" alt="image" src="https://github.com/aptakube/aptakube/assets/135211805/ffce51a6-8bf2-413f-adee-37baf6850fe9">

### Environment & Operating System

macOs Sonoma 14.5 (M1 Max)

**Comment by goenning** [comment]
Thanks @medbayoudh I'll include a fix for this on the next patch version

**Comment by goenning** [comment]
Fixed on 1.6.8, but please reopen the issue if it's not

**Comment by medbayoudh** [comment]
Thanks @goenning 🙏
