### ISSUE TITLE
Ability to create resources

### ISSUE THREAD

**Issue by goenning** [aptakube/aptakube#24]
### What problem are you trying to solve?

Sometimes we really just want to create something manually to test things out and that's not possible in Aptakube currently, there is only View / Edit / Delete

### Describe the solution you'd like

A button to create objects, any object, probably using YAML. Type or paste the yaml and hit apply, should also support multiple objects

**Comment by mschneider82** [comment]
Please Add also a template directory, where a user can put his templates for deployments, ingress etc.
Most users need specific things in the templates like a custom storageClass, annotations for e.g. ingress ...

**Comment by ethaniel86** [comment]
> ### What problem are you trying to solve?
> Sometimes we really just want to create something manually to test things out and that's not possible in Aptakube currently, there is only View / Edit / Delete
> 
> ### Describe the solution you'd like
> A button to create objects, any object, probably using YAML. Type or paste the yaml and hit apply, should also support multiple objects

+1 to this feature, feels good to do most of the stuff in app :)

**Comment by ajaykumarmandapati** [comment]
Hello! 👋🏾  
Firstly, great product, and I liked using it to manage k8s clusters at scale. Is there a tentative or possibility when this might get picked and implemented? This is a show-stopper for us to purchase licenses for our team.

Thanks and Happy New Year in advance! ❤️

**Comment by goenning** [comment]
hey @ajaykumarmandapati thanks for the feedback. This is the second most requested feature, so I'll add this after the first :) 

Should be soon-ish

**Comment by Hassan-Qureshi** [comment]
@goenning what's the most requested feature? Just curious. 😄

**Comment by goenning** [comment]
It's [Node Draining and Cordoning Capabilities within Nodes view #134
](https://github.com/aptakube/aptakube/issues/134)

The list is here:
https://github.com/aptakube/aptakube/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by timopulkkinen** [comment]
Any news on this? Would help a lot to prevent any mishaps when managing multiple clusters.

**Comment by goenning** [comment]
This is on my plans for 1.7.0, which is the next version I'll release after my summer break. Soon!

**Comment by goenning** [comment]
Work in Progress :)

https://github.com/user-attachments/assets/7f131884-d4eb-45c5-86fd-9a04447511ba

**Comment by mschneider82** [comment]
@goenning thanks, is the [custom template also planed for future releases?](https://github.com/aptakube/aptakube/issues/24#issuecomment-1545792552)  

currently the namespace is always default even when a specific namespace is selected.

**Comment by goenning** [comment]
I opened a separate issue to track templates: https://github.com/aptakube/aptakube/issues/271

I don’t have a date, but it’s something I want to improve

but my understanding is that in most cases people will just copy/paste the YAML rather than hand-writing them inside the app.
