### ISSUE TITLE
Add cluster alias name

### ISSUE THREAD

**Issue by trombini77** [aptakube/aptakube#240]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Today the cluster name appears reduced in the left column:
![image](https://github.com/aptakube/aptakube/assets/13336060/99014bac-059f-4087-9f8d-02349e0df554)

This leads to errors in many windows with different clusters.

So I believe that adding a single Alias name to a cluster context (with or without a custom icon) helps to see easy in what cluster you´re working.

**Comment by goenning** [comment]
Hey Leandro,

what I usually recommend doing in this case is simply renaming the context in your Kubeconfig, for 2 reasons:

1) that’ll keep the name consistent as you move across tools
2) it’ll make your life much easier when running command in Kubectl as it’s easier to switch context if the name is small and memorable 

Only the “context.name” has to be changed, you can keep the cluster name as is (the long AWS formatting)

As for icons, that’s supported and documented here ( https://aptakube.com/docs/contexts ) alongside context groups and order.
These settings are also located in your kubeconfig, meaning you can share your setup with team members.

Would that work for you?

**Comment by trombini77** [comment]
Yes it worked at this way.
Thanks for that.
