### ISSUE TITLE
Filter field search labels and annotations

### ISSUE THREAD

**Issue by trombini77** [aptakube/aptakube#244]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

A feature that is well known in Lens is the ability to search filed look labels and annotations keys and fields.

For example, if you have a custom label in a group of nodes, that is very usual, with a filter, it would be easy to show only the nodes that match the string. The same would work for Pods and other objects.

Did somebody request it?

**Comment by goenning** [comment]
Closing this in favour of https://github.com/aptakube/aptakube/issues/177
