### ISSUE TITLE
Log Viewer - Allow context menu, copy / paste

### ISSUE THREAD

**Issue by nicholas-ochoa** [aptakube/aptakube#247]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Currently the log viewer does not have a right click context menu, and if you select text and press `CMD+C` or even `CTRL+C` it just beeps and does not copy anything. 

- Add a basic context menu with copy, paste, maybe even download logs?
- Allow `CMD+C` / `CTRL+C` to copy select log text
- Allow `CMD+A` / `CTRL+A` to select all text

Edit: Weirdly, in testing out `CMD+C` again it seems to work sometimes. I also noticed that if you select text and then use the menubar and go to `Edit -> Copy` that also seems to work pretty consistently. So maybe just a bug?

**Comment by goenning** [comment]
`Weirdly, in testing out CMD+C again it seems to work sometimes`

Have you noticed any pattern when it does not work? I tried reproducing it but I'm able to copy it consistently

I like the other 2 suggestions too

**Comment by nicholas-ochoa** [comment]
I've noticed it many times before and hilariously once I opened an issue on it, it has seemed to go away. If it occurs again I'll see if I can narrow things down and rule out anything on my machine as well that may be conflicting.

**Comment by vishnu-deepsource** [comment]
I have never had the copy work, and I end up manually kubectl'ing to grab logs.

**Comment by jobace78** [comment]
I'm also unable to copy anything from log view (macOS 15.1 + aptakube 1.8.1)

**Comment by goenning** [comment]
I'm working on this at the moment, anyone interested in trying this beta to see if it's fixed for good?
https://releases.aptakube.com/Aptakube_1.8.2-beta1_universal.dmg

I also added the option to select all lines with `CMD+A`

**Comment by williamohara** [comment]
I noticed the exact same pattern as @fprovencherdrw - 

On Windows Pro
I select then I hit CNTL-C immediately - it copies the selection to my clipboard as expected
- but-

If I select and a wait (The time varies - I tried a few times and found I have anywhere between 4 and 12 seconds to hit CNTL-C after I select the text).  

If i try right-clicking to get a context menu - nothing happens.

@goenning I sent you an email with my system info. let's communicate through here.

**Comment by goenning** [comment]
@williamohara @jobace78 the fix was added to version 1.9.0, which was released yesterday. Can you give it a try to see if it’s fixed?

**Comment by jobace78** [comment]
Hi,

Seems to be working correctly, thanks :-)

**Comment by williamohara** [comment]
seems to be working now! Thanks!
