### ISSUE TITLE
Only 50 elements are displayed after sort

### ISSUE THREAD

**Issue by nicraMarcin** [aptakube/aptakube#248]
### Current and expected behavior

I have 139 pods in my namespace. When I cliks "Pods" all emements are displayed, when I click on Name tab (sorting by name) it displays only 50 elements.
![Screenshot from 2024-06-20 08-02-27](https://github.com/aptakube/aptakube/assets/1545069/3d6b7dad-6fd5-4a8d-bf49-7bf73d245729)
![Screenshot from 2024-06-20 08-02-20](https://github.com/aptakube/aptakube/assets/1545069/278caf2f-1168-410d-a61c-bb8d8e9cd8d7)

### Environment & Operating System

Ubuntu 22.04

**Comment by goenning** [comment]
The app shows the first 50 rows and as you scroll down, it'll load more, but it seems like you have a very very tall monitor + the app is in full screen. 

Can you try making it smaller just to confirm this is the issue?

**Comment by nicraMarcin** [comment]
@goenning I use 4K monitor and app is not in full screen. As you can see only 50 first rows are displayed and I cannot scroll - there is nothig to be scrolled,
but when I reducing window size to be smaller than for 50 rows it seems that it works as expected - it can be scrooll and all pods are shown.
Problem is when window size can fit more than 50 rows.

**Comment by goenning** [comment]
Thanks for conforming, that'll help me troubleshooting and fix it

**Comment by goenning** [comment]
Fixed on 1.7.0, but please reopen if the issue persists.
