### ISSUE TITLE
Azure AKS Entra auth support

### ISSUE THREAD

**Issue by jeroenrinzema** [aptakube/aptakube#257]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

AKS has the ability to use Microsoft Entra to grant access to a k8s cluster. AptaKube at the moment does not handle the login prompt and causes the UI to become unresponsive.

A current workaround is to open a terminal window and execute any `kubectl` command and logging in manually. Once logged in you have to restart AptaKube to connect to the given cluster.

It would be great if AptaKube could open a browser and pass the device auth code to allow the user to log in. `https://login.microsoftonline.com/common/oauth2/deviceauth?code=B24ZD6FP8`

```
$ kubectl run nginx-dev --image=mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine --namespace dev

To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code B24ZD6FP8 to authenticate.

pod/nginx-dev created
```

**Comment by goenning** [comment]
Hi Jeroen,

Aptakube supports Microsoft Entra, however only the non-interactive sign in methods like Azure CLI. You’ll need to switch from Device Code to Azure CLI, which in my opinion makes is a lot better and even using kubectl becomes better.

I wrote an article on how to do it https://aptakube.com/blog/how-to-use-azure-kubelogin

After you sign in with “az login”, aptakube will then be able to generate auth tokens to connect to your AKS cluster.

let me know how it goes!

**Comment by goenning** [comment]
I'll close as I didn't hear back from you, but please reopen if the issue persists
