### ISSUE TITLE
Unable to set custom kubeconfig location

### ISSUE THREAD

**Issue by elmariofredo** [aptakube/aptakube#26]
### What problem are you trying to solve?

I have multiple kubeconfig files for each cluster. I'm unable to tell the app location where it should look for kubeconfig.

### Describe the solution you'd like

I would like to drag and drop kubeconfig files into app window.

**Comment by goenning** [comment]
Hey @elmariofredo, thanks for your suggestion. I'm always interested in learning how people manage their config files, especially those with many clusters/files.

---

How do you use kubectl today? Do you always pass the `--kubeconfig` param? Have you considered using the $KUBECONFIG environment variable or is it not suitable for your workflow?

**Comment by elmariofredo** [comment]
I have two ways to access K8s clusters, primary using Lens app, where I have added clusters kubeconfig files manually and secondary using KUBECONFIG set in each project folder using [direnv](https://direnv.net) tool.  Environment variable is working for me just not for UI tool where it doesn't make IMHO much sense.

**Comment by goenning** [comment]
Got it, thanks for sharing your setup.

For now, the best workaround is to set the KUBECONFIG variable globally. The other is to set the variable per session and then open the app via the terminal. 

But I'll look into how we can add something similar to Aptakube 👍

**Comment by goenning** [comment]
Just an FYI that on Aptakube 0.8.0 there's support for an additional environment variable named `APTAKUBECONFIG`, which works exactly like `KUBECONFIG`, but is exclusive to Aptakube.

I still intend to add a UI to set custom kubeconfig location in a future release, which would make it a lot more user friendly. But this could a quick win for those who want to use custom paths without impacting existing kubectl workflow.

**Comment by elmariofredo** [comment]
> I still intend to add a UI to set custom kubeconfig location in a future release, which would make it a lot more user friendly. But this could a quick win for those who want to use custom paths without impacting existing kubectl workflow.

Great, looking forward to that 🙂

**Comment by goenning** [comment]
Note to self: I had a few more people asking for this too

**Comment by goenning** [comment]
Coming soon 😊

![image](https://user-images.githubusercontent.com/94755/216954932-d15d4c86-23ac-4c52-9dde-bbb48fcce0cf.jpeg)

**Comment by goenning** [comment]
It's been a while, but it's finally live! @elmariofredo in case you're still using Aptakube, give it a try on version 1.2.0 and let me know what you think about it!

**Comment by elmariofredo** [comment]
Nice 👍 Thanks!
