### ISSUE TITLE
Ability to configure columns

### ISSUE THREAD

**Issue by SB-MFJ** [aptakube/aptakube#261]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

I FREAKING LOVE THIS APP. You guys rock. (I've been hopping around since OpenLens is no longer updated)

If I could sort the columns/ chose what column appears, this would genuinely be the best Kubernetes GUI to exist.
For now, though, I'll settle for tiny text to fit all the columns on the screen.

**Comment by goenning** [comment]
I'll close this in favour of https://github.com/aptakube/aptakube/issues/92, which I'll add to the next version :)
