### ISSUE TITLE
Error deleting non namespaced resources

### ISSUE THREAD

**Issue by filipevrevez** [aptakube/aptakube#262]
### Current and expected behavior

When trying to delete non namepaced resources you'll receive an error saying 'missing namespace'.
This happens on the resource view and does not on the resources lists such as cert-manager cluster issuer list
![image](https://github.com/user-attachments/assets/3a12a826-eca1-49dc-8826-0c1a40a22bc5)

### Environment & Operating System

MacOS

**Comment by goenning** [comment]
Oops, good catch. I have a fix for it on the next version. Thanks for reporting.

**Comment by goenning** [comment]
Fixed on 1.7.0, but please reopen if the issue persists.
