### ISSUE TITLE
Can't delete VolumeSnapshotContent objects

### ISSUE THREAD

**Issue by redbaron** [aptakube/aptakube#264]
### Current and expected behavior

K8S 1.29, I can't delete VolumeSnapshotContent objects from UI:

![image](https://github.com/user-attachments/assets/cb8eab9e-5c34-4ef5-bacb-e3b43f4c0b3a)

### Environment & Operating System

Kubernets 1.29
Aptakube Version 1.6.10 (20240617.144003)

**Comment by goenning** [comment]
Oops, good catch. I have a fix for it on the next version. Thanks for reporting.

**Comment by goenning** [comment]
Fixed on 1.7.0, but please reopen if the issue persists.
