### ISSUE TITLE
Ability to enter a new yaml file to deploy from UI

### ISSUE THREAD

**Issue by solidblu** [aptakube/aptakube#270]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

When connected and troubleshooting applications in the cluster if the deployment yaml isn't fully applied or if you want to stand up a quick test pod you need to use kubectl rather than just being able to quickly apply a yaml from the ui like when a person makes edits to an existing yaml.

**Comment by goenning** [comment]
What a coincidence, I'm working on this feature today.

Would this work for you?

https://github.com/user-attachments/assets/b5d9dd42-7f85-4b1b-a041-16b40dcd4d76

**Comment by solidblu** [comment]
This is exactly how I imagined this working when I wrote the request.  Wow!

**Comment by goenning** [comment]
This is available on 1.7.0 now 🚀
