### ISSUE TITLE
Delete Action Shows Wrong Item

### ISSUE THREAD

**Issue by khalid244** [aptakube/aptakube#272]
### Current and expected behavior

In the latest release (Version 1.7.0, 20240812.105827), right-clicking an item to delete it incorrectly displays the name of a different item. This issue occurs because the system is saving the name of the last selected item.

### Environment & Operating System

Mac OS  Aptakube (Version 1.7.0, 20240812.105827)

**Comment by goenning** [comment]
Hmm, that should be expected. When you select an item and open the context menu, you’re performing an action on the selected item

**Comment by khalid244** [comment]
If I select one item and then right-click another item to delete, it will delete the first item instead.

**Comment by khalid244** [comment]
The main issue is that there's no way to deselect items.

**Comment by goenning** [comment]
you can press ESC to deselect all, but I understand how this can be confusing. 
Will see what I can do to improve

**Comment by goenning** [comment]
This behaviour changed on 1.7.1, is it better?
