### ISSUE TITLE
Enter/Return key not working in cmd+k dialog

### ISSUE THREAD

**Issue by jwhitcraft** [aptakube/aptakube#275]
### Current and expected behavior

Hello,

when I press <kbd>cmd</kbd> + <kbd>k</kbd> to open the `jump to` menu, i can type in find what I want, but the arrow keys and enter key are used nothing happens

This was working in 1.7.0 but broke in 1.7.1

### Environment & Operating System

macOS 14.6.1, k8s 1.29+

**Comment by mboutet** [comment]
Additionally, pressing `ESC` after pressing `CMD + K` no longer exits the `jump to` menu. `CMD + K` also no longer works when in the log view.

**Comment by goenning** [comment]
Oops, that’s a regression. Will fix it today. Thanks for reporting

**Comment by goenning** [comment]
🐞 1.7.2 has a fix for this

**Comment by jwhitcraft** [comment]
Appropriate the quick fix @goenning !!

**Comment by mboutet** [comment]
@goenning It seems like the shortcuts (notably `cmd + k` and `cmd + f`) still don't seem to work when the logs viewer is in focus in 1.7.2. More specifically, they don't work when clicking anywhere where the logs are being shown, but they seem to work if clicking somewhere outside where the logs are displayed.

**Comment by mboutet** [comment]
Shortcuts also don't work when focused in the YAML editor. I believe they did before.

**Comment by goenning** [comment]
@dagobertdocker I'll have a fix for this on 1.7.4, thanks for reporting it!

**Comment by goenning** [comment]
The fix for the fix is available now on 1.7.4 😂

Hopefully for good now!
