### ISSUE TITLE
You're charging my card when i already have a yearly subscription paid for by my company

### ISSUE THREAD

**Issue by libracoder** [aptakube/aptakube#279]
### Current and expected behavior

Do not charge my card when I have an active subscription.

### Environment & Operating System

MacOS

**Comment by goenning** [comment]
Hey @libracoder 

if you have a license under your email you can use the license manager https://aptakube.com/license-manager to cancel it, and then use the license key from your employer on the app.

Does that help?

**Comment by goenning** [comment]
It’s  impossible for me to correlate your personal license to your employers license, but if you send me an email to goenning@aptakube.com from your personal e-mail I can cancel your license
