### ISSUE TITLE
Nothing to see here message when clicking on resource

### ISSUE THREAD

**Issue by metheu** [aptakube/aptakube#28]
### Current and expected behavior

I just installed Aptakube(Version 0.8.0 (20221213.120743)) and when clicking on a pod to get further details I get a "Nothing to see here" message. Seems like a bug to me.

### Additional context

<img width="1100" alt="Screenshot 2022-12-15 at 01 03 53" src="https://user-images.githubusercontent.com/6337886/207713486-f1341d64-12b9-40d6-b182-a6078e2829f1.png">

### Operating System

macOS Monterey 12.6.1

### Environment

clientVersion:
  buildDate: "2022-11-09T13:28:30Z"
  compiler: gc
  gitCommit: 872a965c6c6526caa949f0c6ac028ef7aff3fb78
  gitTreeState: clean
  gitVersion: v1.25.4
  goVersion: go1.19.3
  major: "1"
  minor: "25"
  platform: darwin/arm64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-10-24T20:36:26Z"
  compiler: gc
  gitCommit: c240013134c03a740781ffa1436ba2688b50b494
  gitTreeState: clean
  gitVersion: v1.24.7-eks-fb459a0
  goVersion: go1.18.7
  major: "1"
  minor: 24+
  platform: linux/amd64

**Comment by goenning** [comment]
Yes, that's a bug and I'm pretty sure this is related to how EKS contexts are named by default.

To work around it, you could rename your context. But I'll get a fix for it tomorrow!

**Comment by goenning** [comment]
Hey @metheu There's a new version 0.8.1 with a fix for this, can you give it a try?

**Comment by metheu** [comment]
@goenning worked. thanks!
