### ISSUE TITLE
Helm - Releases - multi-cluster view does not show the same release name and namespace in two separate clusters

### ISSUE THREAD

**Issue by OliverRC** [aptakube/aptakube#284]
### Current and expected behavior

e.g `Context A` and `Context B`. In each context there is a helm release `my-release` in namespace `my-namespace`

# `Context  A` 
I see `my-release` in `my-namespace`

# `Context B` 
I see `my-release` in `my-namespace`

# Multicluster

I only see `my-release` in `my-namespace` in `Context A` NOT both `Context  A` and `Context B`

Expected:  `my-release` in `my-namespace` should show up in both contexts with the context name column

### Environment & Operating System

AWS EKS, Kubernets 1.30

**Comment by goenning** [comment]
Thanks for reporting @OliverRC , I have a fix for this which should be released tomorrow :)

**Comment by OliverRC** [comment]
Amazing! What a legend!

**Comment by goenning** [comment]
Done! :)

Please reopen if still not working for you.
