### ISSUE TITLE
Ctrl K and Ctrl N stopped working on Windows after 1.7.4 update

### ISSUE THREAD

**Issue by samvtran** [aptakube/aptakube#287]
### Current and expected behavior

👋🏻 Looks like some of the work on the Cmd K shortcut in 1.7.4 broke a couple of the shortcuts on the Windows side.

The only two that seem to be affected are the Ctrl K and Ctrl N shortcuts for the command palette and namespace selector. All of the other shortcuts are still working (though I just noticed Ctrl F shows the webview search box instead of focusing the Filter textbox 🤔). Downgrading to 1.7.3 fixes the problem for now.

Thanks!

### Environment & Operating System

Windows 11

**Comment by goenning** [comment]
Oops :)

Should be fixed on 1.7.5, but let me know if it's not!
