### ISSUE TITLE
Aptakube doesn't display pods under services without explicit selectors

### ISSUE THREAD

**Issue by sijuu** [aptakube/aptakube#289]
Aptakube is not showing Pods associated with Services that use implicit selectors. This occurs when a Service doesn't have an explicit `selector` field, but instead relies on Kubernetes' automatic label matching based on the Service's own labels.

Steps to reproduce:
1. Create a Service without an explicit selector, eg like:
   ```yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: my-service
     labels:
       app: my-app
   spec:
     ports:
     - port: 80
       targetPort: 8080
     

2. Create Pods with labels matching the Service's labels.
3. Open Aptakube and navigate to the Services view.

#### Expected behavior:
Aptakube should display the Pods associated with the Service, as Kubernetes correctly routes traffic to these Pods.

#### Actual behavior:
Aptakube does not show any Pods under the Service.


This issue only occurs for Services without explicit selectors. Services with explicit selectors correctly show associated Pods.


Suggestion:
Update Aptakube to recognize and display Pods associated with Services using implicit selectors, matching Kubernetes' behavior of using the Service's labels for Pod selection when no explicit selector is provided.

### Environment & Operating System

MacOS
Aptakube Version: 1.7.5

**Comment by goenning** [comment]
Oh, I didn’t know that was possible, thanks for sharing that. Will definitely fix it.

**Comment by sijuu** [comment]
I may have overlooked something here. My observations were based on Aptakube itself, as I saw logs under the service without any selectors. This led me to assume that the service works in routing based on other labels, as I was looking at a namespace with one pod and a service without selectors. (However, pods were not being listed, which I guessed was due to a UI bug or something else.)

To clarify the steps:

- We go to Services
- Select a service which does not have selectors
- Look at the logs tab
- We can see logs

It's possible that Aptakube is now showing logs for all pods in that namespace. While looking at another service today without a selector in a namespace with many other pods (and examining logs tab for the service ), I see logs from many other pods in that namespace too.

There seems to be some weird behavior here.

**Comment by sijuu** [comment]
I may have overlooked something here and guess the info I mentioned about implicit selectors is not accurate, confused now. My observations were based on Aptakube itself, as I saw logs under the service without any selectors. This led me to assume that the service works in routing based on other labels, as I was looking at a namespace with one pod and a service without selectors. (However, pods were not being listed, possibly due to a UI bug or something else.)
To clarify the steps:

We go to Services
Select a service which does not have selectors
Look at the logs tab
We can see logs

It's possible that Aptakube is now showing logs for all pods in that namespace. While looking at another service without a selector in a namespace with many pods (and examining its logs tab), I see logs from many other pods in that namespace too.
There seems to be some weird behavior here.

**Comment by sijuu** [comment]
I may have overlooked something here and guess the info I mentioned about implicit selectors is not accurate, and is wrong. But there is a bug here. My observations were based on Aptakube itself, as I saw logs under the service without any selectors. This led me to assume that the service works in routing based on other labels, as I was looking at a namespace with one pod and a service without selectors. (However, pods were not being listed, possibly due to a UI bug or something else.)
To clarify the steps:

We go to Services
Select a service which does not have selectors
Look at the logs tab
We can see logs

It's possible that Aptakube is now showing logs for all pods in that namespace. While looking at another service without a selector in a namespace with many pods (and examining its logs tab), I see logs from many other pods in that namespace too.
There seems to be some weird behavior here.

**Comment by sijuu** [comment]
I can close this and open a bug report for the actual issue ( when service does not have selectors, it shows logs for all pods in that namespace ). Please let me know if thats the right way to move ahead

**Comment by goenning** [comment]
Yeah I think that’d be better. I still need to do some reading though to understand how implicit selectors work, it seems like you have to manually create the EndpointSlice, it that right?

**Comment by sijuu** [comment]
What I told about implicit selectors was wrong.  It does not work that way. Will close this to avoid confusion. Will open a separate bug with the issue faced
