### ISSUE TITLE
Login with OIDC

### ISSUE THREAD

**Issue by 4everyogs** [aptakube/aptakube#29]
Unable to connect to cluster that is setup with OIDC. Is this feature not supported?

**Comment by goenning** [comment]
OIDC is supported, but there are different ways of doing it so it might not support some yet.

1. Would you mind sharing your kubeconfig (redacting any sensitive information)?

2. A screenshot of the error and what OS are you on would also be super useful.

Thanks

**Comment by goenning** [comment]
I've tested it with https://github.com/int128/kubelogin and it works fine. I'll close this for now, but if anyone is having trouble with OIDC just let me know!

Here's a sample video of how the app behaves when using OIDC with short lived tokens (10 seconds in this case, just for demo purposes...)

https://user-images.githubusercontent.com/94755/221902504-969ee0e5-1fbe-4864-84a1-6e96c573bf09.mp4

**Comment by 4everyogs** [comment]
I apologize for the delay, we were trying in windows. Thank you so much for the details and this helpful video.

**Comment by samisonfire** [comment]
@goenning could you please help with OIDC issue.
I can successfully login using kubelogin and manage cluster using aptakube.

but after some time Aptakube return 401: Unauthorized
but I am still able to get and interact with resources using kubectl

**Comment by goenning** [comment]
@samisonfire are you on discord? Would be quick to troubleshoot there

**Comment by samisonfire** [comment]
@goenning yep, I'm in Discord
how can I find you there?

**Comment by goenning** [comment]
@samisonfire join https://discord.gg/FFp9bxHxtx and look for @goenning there, I’m the only admin there with a yellow username
