### ISSUE TITLE
Aptakube showing logs of pods not part of service when there are no selectors

### ISSUE THREAD

**Issue by sijuu** [aptakube/aptakube#290]
### Current and expected behavior

In Aptakube, if we look at logs tab under a service without any selectors, we can still see logs from pods under that namespace.

Steps:
Go to Services
Select a service which does not have selectors
Look at the logs tab
We can see logs

It's possible that Aptakube is showing logs for all pods in that namespace although there are no pods the service is routed to. There seems to be some weird behavior here.

### Environment & Operating System

MacOS
 Aptakube Version: 1.7.5

**Comment by goenning** [comment]
Should be fixed now on 1.7.6, services without selectors will not match any pods
