### ISSUE TITLE
Missing spaces in secrets preview

### ISSUE THREAD

**Issue by jonasled** [aptakube/aptakube#295]
### Current and expected behavior

When previewing secrets containing spaces at the beginning of a line ( e.g. yaml ), the spaces are getting stripped.

![image](https://github.com/user-attachments/assets/2351f88b-ea2e-4266-9f8d-14b6bbfb0d04)

### Environment & Operating System

OS: Arch Linux and windows
Aptakube version: 1.7.5
K8S Version: 1.30.4 ( Talos )

**Comment by goenning** [comment]
Fixed on 1.7.7

**Comment by jonasled** [comment]
Just updated my client and can confirm, secrets are now displayed correctly.
