### ISSUE TITLE
Cannot save log files / worked with version before

### ISSUE THREAD

**Issue by RonStein2000** [aptakube/aptakube#300]
### Current and expected behavior

Command plugin:fs|write_text_file not allowed by ACL

### Environment & Operating System

Mac OS Sequoia (15.0)

**Comment by goenning** [comment]
Oops :) I’ll release a fix for this tomorrow morning

**Comment by zzjin** [comment]
+1 here.

**Comment by goenning** [comment]
should be fixed on 1.7.9 now, thanks for reporting it!
