### ISSUE TITLE
Container Environment Variables Section Doesn't Show Partial Results

### ISSUE THREAD

**Issue by sijuu** [aptakube/aptakube#301]
Variables for pods can be set in multiple ways, including inline, Secrets etc. The current all-or-nothing approach prevents users from seeing any environment variables if they lack permission for just one source (e.g., Secrets).

#### Current Behavior
When a user doesn't have list permissions on secrets, the "Environment Variables" section shows no results and displays an error message:

```
Environment Variables
Error: secrets "xxxx" is forbidden: User "yyy" cannot list resource "secrets" in API group "" in the namespace "zzzz": Forbidden
```

#### Expected Behavior
The section should show the environment variables that the user has permission to view, such as:
- Inline values
- Field path values
- Any other env variables whose source the user has access to

For env variables where the user lacks permission, it should display "Permission Denied" but still show the ones they can access.

#### Suggestion
Implement a partial display feature that shows available environment variables while indicating "Permission Denied" for those the user can't access. .

### Environment & Operating System

MacOS

**Comment by sijuu** [comment]
@goenning can this be fixed. it would be nice to view the variables we have access to in the ui

**Comment by goenning** [comment]
This should be fixed now, so I’ll close this. But please let me know if it’s still happening.

**Comment by sijuu** [comment]
nice, this is better. I can confirm that I am able to view variables having permissions fine. 

I would have preferred even for the ones which I don't have access, the `key` part is shown with the value part ( saying permission denied ) so we know which vars are part of the pod ( now I have to look at yaml to know which are the missing ones )

it that can be done, the better. but not reopening as its better than before and I can live with this. thankyou 👍
