### ISSUE TITLE
Unable to upgrade Aptakube from 1.7.8 to 1.7.9.

### ISSUE THREAD

**Issue by metaad** [aptakube/aptakube#302]
### Current and expected behavior

Unable to upgrade Aptakube from 1.7.8 to 1.7.9 as both installers have same MSI product code {21050BE2-9EF1-5E08-A36F-45260B21F2C2}. Due to this upgrade is not happening.
![Screenshot 2024-09-30 102712](https://github.com/user-attachments/assets/37ced9ba-c0d0-49c9-b59d-bc67c4338b9c)

### Environment & Operating System

Windows 10 and 11 x64

**Comment by goenning** [comment]
Hi, thanks for reporting this.

I was just reading the Microsoft documentation on this and it seems like it’s ok to keep the same ProductCode between different versions: https://learn.microsoft.com/en-us/windows/win32/msi/product-codes

And so I’m a bit confused why that error is happening. I’ll do a bit more research, but if you have more info on this please share! Thanks

**Comment by metaad** [comment]
Hi,

Thanks for the prompt response.
If I try to execute the installer msi of 1.7.9 version, it perfectly installs.
The problem arises when are trying to upgrade from 1.7.8.

**Comment by goenning** [comment]
Oh, I think I know why. I’ll send you a new version later today so you can test it before I officially release, is that ok?

**Comment by metaad** [comment]
Sure, that sounds good.

**Comment by goenning** [comment]
Can you try with this version https://releases.aptakube.com/Aptakube_1.7.10_x64_en-US.msi (not yet publickly released, but soon!)
This one has a new product code

**Comment by metaad** [comment]
Let us know once this version publicly available.

**Comment by goenning** [comment]
It's live now, thanks for reporting this issue!
