### ISSUE TITLE
Keda metrics are not properly interpreted by HPA section in Aptakube

### ISSUE THREAD

**Issue by nodkrot** [aptakube/aptakube#303]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

We are using https://keda.sh/docs/2.14/scalers/apache-kafka/ for HPA target metrics, below the pod should scale based on kafka consumer lag when above 300 but current value is read incorrectly. Im assuming there is no support for this today.
![image](https://github.com/user-attachments/assets/99607d53-b5a9-4057-87ec-5efd9baedf8e)

**Comment by goenning** [comment]
Do you mind sharing the YAML spec+starus for this HPA (redacted any private info)

**Comment by nodkrot** [comment]
> There you go:
> 
> ```
>   maxReplicas: 10
>   metrics:
>     - external:
>         metric:
>           name: s0-kafka-core-events-consumer-topics
>           selector:
>             matchLabels:
>               scaledobject.keda.sh/name: xxx-worker-kafka
>         target:
>           averageValue: "300"
>           type: AverageValue
>       type: External
>   minReplicas: 3
>   scaleTargetRef:
>     apiVersion: apps/v1
>     kind: Deployment
>     name: xxx-worker
> ```
> 
> I did notice that sometimes it pulls correct lag number, 64/300 but on next refresh it would go back to something like 47564m/300

This could be related to https://stackoverflow.com/questions/75210091/keda-with-prometheus-integration

**Comment by goenning** [comment]
Sorry, I'm lost here. So is the issue on the manifest, or in how we render it on Aptakube?

Aptakube basically reads the current value from `status.currentMetrics` and target from `spec.metrics`, it does not perform any formatting when using External metrics sources.

**Comment by nodkrot** [comment]
Suggestion from that stackoverflow makes the metric consistent, just confirming. This is not aptakube issue.
