### ISSUE TITLE
Improve usability of pod Shell submenu

### ISSUE THREAD

**Issue by yseymour** [aptakube/aptakube#305]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Moving the mouse onto the `Shell` context menu of a pod with multiple containers requires a lot of precision:

https://github.com/user-attachments/assets/930b5fac-5e24-4d00-8a8f-95832371e707

It'd be great if the submenu could be aligned with the `Shell` line, and perhaps had a bit of a closing delay to make it easier to transition the mouse on to it.

**Comment by goenning** [comment]
Oops 😬 

Will fix it soon

**Comment by goenning** [comment]
Fixed!

**Comment by yseymour** [comment]
Much better! Thank you!
