### ISSUE TITLE
Don't close YAML editor when request is not accepted 

### ISSUE THREAD

**Issue by gk-fschubert** [aptakube/aptakube#306]
### Current and expected behavior

When creating a resource and the YAML syntax is correct but it don't get applied by k8s, the editing field should stay open until it's accepted. 

![Kapture 2024-10-11 at 10 53 01](https://github.com/user-attachments/assets/8fab52b2-514c-4647-8061-f4be0e780d8a)

### Environment & Operating System

macOS sequoia

**Comment by goenning** [comment]
Thanks! I have a fix for this coming soon

**Comment by goenning** [comment]
Fixed on the last release
