### ISSUE TITLE
navigation bar not visible when "too many" init containers

### ISSUE THREAD

**Issue by gk-fschubert** [aptakube/aptakube#309]
### Current and expected behavior

init containers should be scrollable and the items "Logs, YAML, Events, Search bar, Port forwarding, Delete" etc. should be permanently fixed without the need to scroll there. In addition it seems that the running container is appended at the end of the bar. It should be the first item. 
![Kapture 2024-10-15 at 13 57 33](https://github.com/user-attachments/assets/3cbc7ed5-facc-4d8f-bcb5-3a58a82b04e7)

### Environment & Operating System

macOS sequoia

**Comment by goenning** [comment]
Wow, that’s a lot of init containers

😅

I need to think about how to solve this. I might move the running containers to the left as suggested; and probably have all the init containers on a single tab

Overview | Container1 | Container2 | Init Container | Logs | YAML …

**Comment by goenning** [comment]
Actually, I might just remove the init container tabs. They’re less important than running containers and you can still access them from the overview tab 🤔

**Comment by gk-fschubert** [comment]
> Actually, I might just remove the init container tabs. They’re less important than running containers and you can still access them from the overview tab

Would be also suitable for me

But I think there should be a pagination are something similar because it's also not uncommon - at least for us - to have a few sidecar containers and in the current view it's not obvious that there is more, when you scroll sideways. May when there are more items which fits in the bar, the items could be truncated to 'Running Containers' and 'Init-Containers' with a menu to be able to select just one of them.

**Comment by goenning** [comment]
Fixed it on 1.7.13, tabs are now only visible if you have up to 2 init containers. In other cases, they'll be on the overview tab only
