### ISSUE TITLE
Shell access missing from pod overview

### ISSUE THREAD

**Issue by gk-fschubert** [aptakube/aptakube#311]
### Current and expected behavior

(may not a bug but I don't think it's a feature request)
When you want to access the shell of a container, there are currently the ways(as far as I know): 
- right click on the pods running in a deployment/daemonset etc. 
- click on the pod, then on the actual container and then there is a shell icon in the upper right corner

I'm missing a right click option in the pod overview to access to a running container 
![Kapture 2024-10-16 at 15 59 11](https://github.com/user-attachments/assets/adbd9534-bbbe-4e5f-8035-2de4d982ec90)

### Environment & Operating System

macOS sequoia

**Comment by goenning** [comment]
yeah, not a bug, but this is actually a great suggestion.

Coming on the next patch 

![Screenshot 2024-10-17 at 14 44 03](https://github.com/user-attachments/assets/ddc922cd-012b-41e1-8eba-d663636a5139)

**Comment by goenning** [comment]
Available now on 1.7.13
