### ISSUE TITLE
Unable to login into cluster

### ISSUE THREAD

**Issue by teffcz** [aptakube/aptakube#315]
### Current and expected behavior

I am unable to login to multiple clusters with valid kubeconfigs and it is working in other IDEs (k9s and lens)

From logs of aptakube i can see:
[2024-10-23][12:59:41][ERROR][Kd@tauri://localhost/assets/index-BK3LhC2U.js:11:23042] failed to fetch CRDs: 401: Unauthorized: Unauthorized

Can it be somehow solved?

### Environment & Operating System

MacOs seqoia 15.1,  latest aptakube, multiple clusters ranging from version 1.20 to 1.31.1

**Comment by goenning** [comment]
1. Is it just the CRD that's not working? Or do you get an error like this?

![Screenshot 2024-10-23 at 14 22 02](https://github.com/user-attachments/assets/7837c32d-367b-40f9-a896-d4b131a4cdde)

2. Do you have any kubeconfig with duplicate `user` section? Aptakube is basically merging all your kubeconfigs so if config1.yaml has user A and file config2.yaml also has user A, they might end up getting mixed. This is usually what's the source of Auth issues.

**Comment by teffcz** [comment]
Error like on the screenshot.

I will validate user sections and provide update about this issue

![image](https://github.com/user-attachments/assets/0c3c7444-5ca0-44e4-8b81-73791e7eb21e)

**Comment by goenning** [comment]
Thanks for the screenshot.

1. Would also be interesting to know what auth method is being used, token? oidc? certs? exec plugin?
2. Try starting the app from your terminal via `open -n /Applications/Aptakube.app` to see if that fixes it

**Comment by goenning** [comment]
I'll close this as it's been resolved, but I'll follow up with improvements via https://github.com/aptakube/aptakube/issues/326
