### ISSUE TITLE
Unable to open app after upgrade to 1.7.13

### ISSUE THREAD

**Issue by mboutet** [aptakube/aptakube#316]
### Current and expected behavior

<img width="259" alt="image" src="https://github.com/user-attachments/assets/1e272298-f247-4505-9d6d-6eb6016f8850">

### Environment & Operating System

Apple M2 Max
13.6.2 (22G320)

**Comment by goenning** [comment]
ouch, that's right after you start the app? or after you take an action?

**Comment by mboutet** [comment]
> ouch, that's right after you start the app? or after you take an action?

Yeah, right after starting it.

**Comment by mboutet** [comment]
Maybe there's some kind of cache folder I could clear? Do you know if there's such folder?

**Comment by mboutet** [comment]
Still the same issue after cleaning up those files and reinstalling the latest version.

 think this might be related to some new security/compliance stuff in our corporate environment. I've tried to reinstalled from the self service internal platform and it works, but it's still on version 1.6.4. I'll reach out internally so they publish a new version.

**Comment by goenning** [comment]
That's odd, I'm curious to hear more about it if you manage get 1.7.13 running again and if your company made any recent changes that could have caused this, so that I can handle it better

**Comment by mboutet** [comment]
I'll try to get back to you on this.

**Comment by mboutet** [comment]
Upgrading to Sonoma (`14.4.1 (23E224)`) made the issue go away 🤷🏼 

Thank you again
