### ISSUE TITLE
Pod logs get scrambled

### ISSUE THREAD

**Issue by thonby** [aptakube/aptakube#317]
### Current and expected behavior

Expected: Logs are shown in a readable form

Current: Logs are a mess, although they at times show clearly. The screenshot explains this best.

I *think* this started with version 1.7.12

![Screenshot from 2024-10-23 19-12-02](https://github.com/user-attachments/assets/ad13adf9-dca6-4607-9b10-7ad4b41c3564)

### Environment & Operating System

Debian Linux, Bookworm, 6.1.0-26 kernel

**Comment by SoGooDFR** [comment]
This is a regression, I can confirm it.

### Environment & Operating System
Ubuntu 24.04LTS - 4K screen

**Comment by goenning** [comment]
Thanks, I’ll look into this soon.

Does 1.7.11 work as expected?

https://github.com/aptakube/aptakube/releases/tag/1.7.11

**Comment by SoGooDFR** [comment]
Same with 1.7.(11/10/9). I suspect linux gtk depency regression

**Comment by goenning** [comment]
I couldn't reproduce this on my Ubuntu 22.04 laptop.

1. What's the version of your `libwebkit2gtk-4.0-dev` package, is it the latest?
2. Are you using the .deb or .AppImage?
3. could you try this beta version:
- https://releases.aptakube.com/aptakube_1.7.14-beta1_amd64.AppImage
- https://releases.aptakube.com/aptakube_1.7.14-beta1_amd64.deb

**Comment by SoGooDFR** [comment]
1. I don't have this package and from an issue (https://github.com/tauri-apps/tauri/issues/9662), ubuntu removed it.
2. I'm using .deb
3. Same problem :/

**Comment by goenning** [comment]
sorry, I was meant to say `libwebkit2gtk-4.1-dev` 🤦‍♂️

**Comment by goenning** [comment]
I was finally able to reproduce, and hopefully fix it!

So here's another beta if anyone wants to give a try and share your feedback.

https://releases.aptakube.com/aptakube_1.7.15-beta1_amd64.deb

**Comment by goenning** [comment]
I’ll release it tomorrow as stable, thanks for confirming it’s working.
