### ISSUE TITLE
Panic and crash when connecting to cluster

### ISSUE THREAD

**Issue by lpiwowarek-sugarcrm** [aptakube/aptakube#319]
### Current and expected behavior

# Issue

App crashes with the following log when connecting to any cluster:

`[2024-10-24][14:53:40][[31mERROR[0m][aptakube] Panicked: PanicHookInfo { payload: Any { .. }, location: Location { file: "/Users/goenning/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kube-client-0.95.0/src/client/auth/oidc.rs", line: 314, col: 14 }, can_unwind: true, force_no_backtrace: false }`

# Expected behavior

App connects and opens cluster view.

# Additional notes

This started happening a month or two ago, I should have written down the version at the time but I forgot and I haven't had a chance to look into it more until now. Updated to latest today and the issue persists.

Cluster API is ODIC protected.

The path indicated in error does not exist on my system, is this something internal to the application?

Let me know if I can provide additional details

### Environment & Operating System

macOS Sonoma 14.6.1
Kubernetes v1.30.3 (kOps on EC2)

**Comment by goenning** [comment]
would you mind trying this pre-release?

https://releases.aptakube.com/Aptakube_1.7.14-beta1_universal.dmg

**Comment by lpiwowarek-sugarcrm** [comment]
@goenning this works!

**Comment by goenning** [comment]
Fixed on 1.7.14, but please reopen if the issue persists!
