### ISSUE TITLE
Unable to open app after update 1.7.12

### ISSUE THREAD

**Issue by jacob-m-barnes** [aptakube/aptakube#320]
### Current and expected behavior

Updated app to 1.7.12 and app would crash at startup.  Deleted and re-installed and was met with the same issue, so I deleted again and re-installed version 1.7.8 and was able to get back to a working state.  

Tried again with version 1.7.13 and was met with the same issue. Reverting to 1.7.8 fixed it again. 

### Environment & Operating System

Intel macOS Ventura 13.2.1

**Comment by goenning** [comment]
Seems similar to https://github.com/aptakube/aptakube/issues/316

But the fact that it works on 1.7.8 gives me a hint into what could be causing this. Will try a fix tomorrow.

Have you tried 1.7.9? Does it also crash?

**Comment by goenning** [comment]
Update: I'm not sure if this fixes it as I'm not on Ventura, but would you mind trying this pre-release?

https://releases.aptakube.com/Aptakube_1.7.14-beta1_universal.dmg

**Comment by jacob-m-barnes** [comment]
I was able to launch v 1.7.14-beta1 successfully 🎉

**Comment by goenning** [comment]
Nice, thanks for the update!

**Comment by goenning** [comment]
Fixed on 1.7.14, but please reopen if the issue persists!
