### ISSUE TITLE
Port Forwarding on Container Screen

### ISSUE THREAD

**Issue by RickJAtWork** [aptakube/aptakube#321]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Currently if I want to port forward I can do it from the pod overview but not the container tab. The issue there is I don't always know what port I want to forward so I have to look on the container and see which ports are exposed. Then I have to click back to the "Overview" tab in order to forward the port.

It would be great if one or both of these could happen...
1. Add the port forward button beside the Open Shell button on the container tab
2. Under the ports section of the container display place a button next to each port instance that automatically opens the port forward prompt with the port pre-selected.

Thank you!

**Comment by goenning** [comment]
I love your second option, and it's easy to add it! 
Keep an eye out for the next patch release!

**Comment by RickJAtWork** [comment]
I'll give you an example where Option 1 might be helpful - however using Option 2 but then just making a different port selection could be a work around.

I have a container that uses a liveness probe on a specific port and I wanted to test it locally so I wanted to forward that port. I had to check the container page for what port the probe used, then go back to the overview page to forward it. It's not part of the "ports" list so I couldn't use any of the values in the drop down but I could use custom and put in my own port.

Maybe this is too specific a situation to design for? Like I said - I could just click port forward beside one of the ports in the list, then change to custom and enter the probe port that I'm looking at. But I wanted you to be aware should you have any brilliant ideas from it!

Thank you again! Awesome product!!

**Comment by goenning** [comment]
I decided to go with the shortcut to port forward beside each port on 1.7.14

The shortcut does not automatically start port forward, so you'd still have the option to change it to a "custom port" for the probe port

Thanks for the suggestion!
