### ISSUE TITLE
UI: New Window opens as much windows sa are currently opened

### ISSUE THREAD

**Issue by jjuris** [aptakube/aptakube#322]
## Current behavior
As described in the title, if there is one window opened, then new window opens one window. If there are two windows already opened, then another two windows are opened. Basicaly New Window action multiplies opened windows by 2.

## Expected behavior
Only one new window is opened.

Thank you

### Environment & Operating System

MacOS 14.5 (23F79)
Aptakube Version 1.7.14 (20241028.122538)

**Comment by goenning** [comment]
maybe I should rename it to `Duplicate Windows` 😂

I have a patch scheduled for tomorrow, and I'll include this fix as well

**Comment by goenning** [comment]
Fixed on 1.7.15
