### ISSUE TITLE
unable to start appimage after update to 1.7.14 - and 1.7.16

### ISSUE THREAD

**Issue by cdreier** [aptakube/aptakube#324]
### Current and expected behavior

just (auto) updated the appimage version from 1.7.13 to 1.7.14 on fedora, and aptakube is just a white screen when starting.

the error in the console is 

```
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...
```

also downloaded fresh copy from github, still the same issue

### Environment & Operating System

fedora 40

**Comment by goenning** [comment]
Are you using the AppImage or .rpm?

**Comment by goenning** [comment]
sorry, just noticed the title 🤦

does the 1.7.13 still work?

**Comment by cdreier** [comment]
yes, just tested 1.7.13 ist still fine

**Comment by goenning** [comment]
Seems like there's a recent regression on WebKitGTK (https://www2.webkit.org/show_bug.cgi?id=280239) and the latest release went out with the newest version of it.

It doesn't seem to impact Ubuntu though, as 1.7.14 worked fine here.

Would you mind trying this beta release please?

https://releases.aptakube.com/aptakube_1.7.15-beta1_amd64.AppImage

**Comment by goenning** [comment]
Fixed on 1.7.15

**Comment by cdreier** [comment]
sorry for the delayed feedback, thanks for the fix, was able to test it and it's working fine !

**Comment by cdreier** [comment]
Hi @goenning - i just installed 1.7.16 and the problem with the white screen is back - can we reopen this issue?

**Comment by goenning** [comment]
Oops, let me check my Ubuntu machine, the packages might have auto updated

**Comment by goenning** [comment]
@cdreier would you confirming this one works before I release it?

https://releases.aptakube.com/aptakube_1.7.17_amd64.AppImage

**Comment by cdreier** [comment]
@goenning yes, it's working :+1:

**Comment by goenning** [comment]
Thanks! Released on https://github.com/aptakube/aptakube/releases/tag/1.7.17
