### ISSUE TITLE
Cannot connect to cluster

### ISSUE THREAD

**Issue by SWojtyla** [aptakube/aptakube#33]
### Current and expected behavior

When trying to connect to my aks cluster I always get an authentication error. 
Here is what I'm getting:
![image](https://user-images.githubusercontent.com/36441058/208633528-3169abd0-e328-4ba6-8cc7-d843f8252b71.png)

I don't think that this is related to my config since in Lens I can see my clusters/pods without any problem:
![image](https://user-images.githubusercontent.com/36441058/208633723-5f851215-d6fa-4413-bb15-32b26b6d2ef7.png)

Any idea what could be the issue ? Is there an issue with the Azure login or am I missing some settings ? I also switched to Azure kubelogin.

### Operating System

Windows 11

### Environment

clientVersion:
  buildDate: "2022-06-15T14:22:29Z"
  compiler: gc
  gitCommit: f66044f4361b9f1f96f0053dd46cb7dce5e990a8
  gitTreeState: clean
  gitVersion: v1.24.2
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: windows/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-11-09T17:12:37Z"
  compiler: gc
  gitCommit: c23d69c673335261c7029c60c877d81c9bfef2a8
  gitTreeState: clean
  gitVersion: v1.24.3
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: linux/amd64

**Comment by goenning** [comment]
hey @SWojtyla are you using kubelogin 0.0.21 or older? If yes, could you try updating it? There is a bug on some older versions that is impacting Aptakube https://github.com/Azure/kubelogin/issues/150

As well as, can you confirm your server-id is `6dae42f8-4368-4678-94ff-3960e28e3630` (this is a not secret 🙂)

**Comment by SWojtyla** [comment]
Seems like I was indeed using an old version... 
And indeed that's the server-id, didn't know it was public.
Thought it was an issue with aptakube since it was working in lens somehow.. 

But now it's working perfectly !
Thanks for your help !!

**Comment by goenning** [comment]
Hey @SWojtyla It’s sort of a bad combination of kubelogin expecting an environment variable that is not really mandatory, and which Aptakube does not support yet. I’ve added that to the next version of aptakube so it’ll work with kubelogin 0.0.21 as well.

Glad to know it worked for you! Let me know if you have any feedback or suggestions on Aptakube. 

Thanks.
