### ISSUE TITLE
Merging of kubeconfigs is now disabled by default!

### ISSUE THREAD

**Issue by JTheinert** [aptakube/aptakube#330]
### Current and expected behavior

Sadly now the merging of kubeconfigs is disabled by default, this causes issues for us since we have built our kubeconfig generation specifically to enable merging. It would be great if you'd introduce a switch to turn on/off merging of the configs.
Right now this prevents our team from updating to the newest version. 

#326 

### Environment & Operating System

MacOs Sonoma and Kubernetes 1.29

**Comment by goenning** [comment]
I was almost certain this would happen :)

I have a near-working version with optional merging, so I will try get it working soon and send you a beta to confirm.

Quick question for you: do you have all your to-be-merged files in the same folder?

**Comment by goenning** [comment]
Would you mind trying this preview build? There's a toggle under "kubeconfig" settings for merge

https://releases.aptakube.com/Aptakube_1.8.0-beta1_universal.dmg

**Comment by JTheinert** [comment]
@goenning yes that seems to work, the only thing I noticed is that it's merging all the files in the .kube folder. Sadly, in my case, it's also merging a kubectx file. Where my current context is saved, is there a possibility that this will be excluded?

**Comment by goenning** [comment]
> Sadly, in my case, it's also merging a kubectx file

Sorry can you expand on this? I use kubie instead of kubectx, I'm not sure what's a `kubectx file`. 

Is it a kubeconfig file generated by kubectx when you select a cluster? does it have a fixed/well-defined name?

**Comment by JTheinert** [comment]
> > Sadly, in my case, it's also merging a kubectx file
> 
> Sorry can you expand on this? I use kubie instead of kubectx, I'm not sure what's a `kubectx file`.
> 
> Is it a kubeconfig file generated by kubectx when you select a cluster? does it have a fixed/well-defined name?

Yes I can, It's essentially just a file which stores the current context. This file will be created in the .kube folder. Therefore, in my case with merging all the files in that folder, I get an error. The kubectx file just stores a string of the K8s Cluster you are currently in. 

For now I fixed it by manipulating kubectx, but maybe I need to take a look at kubie :D

**Comment by goenning** [comment]
Thanks, I'll close this as the initial issue is solved. 

I'm still trying to decide if I want to ignore files that don't look like Kubeconfig as that could silently ignore real issues..
