### ISSUE TITLE
Number of namespaces in filter not correct.

### ISSUE THREAD

**Issue by RonStein2000** [aptakube/aptakube#333]
### Current and expected behavior

On each window I can select or more namespaces. But the number of selected namespaces does not match, what I have actually selected, when I switched back and forth with some selections. The number should always reflect the number of selected namespaces, otherwise it is confusing. Even better, I would like to see the one namespace name itself, if its the only selected and the number only, if 2 or more are selected.

### Environment & Operating System

Mac OS 15.1

**Comment by goenning** [comment]
I’ll look into it, but do you mind sharing a screenshot of the issue so it’s easier for me to understand?

**Comment by goenning** [comment]
This is how it should look when you have 3 selected namespaces, for example

![Screenshot 2024-11-18 at 09 28 00](https://github.com/user-attachments/assets/ed3da270-e2b3-4b83-b6d1-1d319ce9afe5)

or a single namespace
![Screenshot 2024-11-18 at 09 28 30](https://github.com/user-attachments/assets/d6526111-9ed1-462a-9945-c0811d2d9f28)


are you seeing something different?
