### ISSUE TITLE
Make updates less intrusive

### ISSUE THREAD

**Issue by zerodayyy** [aptakube/aptakube#338]
### Current and expected behavior

At the moment Aptakube update notifications are extremely intrusive, and given that new versions come out quite often I find it a nuisance.

When a new version is released, on launch the user is interrupted twice — with (1) the upgrade modal and (2) "restart now" modal

It would be great to change the blocking pop-ups on launch to something less distracting, for instance:
- a "update available" notice in the toolbar or a notification badge on settings gear icon
- automatic upgrade with a config option to disable it

### Environment & Operating System

Version 1.8.1 (20241118.190807)

**Comment by goenning** [comment]
There's an option under `General -> Disable automatic updates` which maybe I need to label it better.

But it basically disables the blocking popups, but still show this notification on bottom right.

Does that help?

![image](https://github.com/user-attachments/assets/3f54c38c-86b0-4182-8fb1-84e0e3db1f8e)

**Comment by zerodayyy** [comment]
@goenning that's exactly what I needed, thanks a lot! Perhaps it can be labeled better indeed

**Comment by goenning** [comment]
The startup blocking update popup was removed from 1.9.1
