### ISSUE TITLE
Context selection not showing selected item

### ISSUE THREAD

**Issue by MattKetmo** [aptakube/aptakube#339]
### Current and expected behavior

Hello, 

I noticed several minor issues on context selection (the 1st page).

First looks like there is a margin/padding issue which prevent the full item outline to be displayed correctly
![CleanShot 2024-11-21 at 17 12 03@2x](https://github.com/user-attachments/assets/a7a7e916-eb15-4301-9371-366ce8d82700)
![CleanShot 2024-11-21 at 17 07 20@2x](https://github.com/user-attachments/assets/49f9de0c-7d9f-437c-911a-6f85abe397c2)

Sometimes there is no outline at all (in the screenshot bellow, the 3rd element are selected but you don't see it)
![CleanShot 2024-11-21 at 17 07 14@2x](https://github.com/user-attachments/assets/1c9d238c-d3c3-4433-8d19-701ce33592eb)

And finally a bug prevent me to select the last element. Here in that screenshot the 4th element is selected, but if I tap arrow down it doesn't select the last element.

![CleanShot 2024-11-21 at 17 07 27@2x](https://github.com/user-attachments/assets/14b99383-6f7b-4db9-ad34-d1258e6fc39a)

Looks like this last issue is related to the context group:
- with 1 context group at the top, I can't select the last element with keyboard
- with 3 context groups at the top, I can't select the last 3 elements with keyboard

### Environment & Operating System

macOS 14.6.1
Aptakube 1.8.1

**Comment by MattKetmo** [comment]
Btw, I'm not sure what you use for the outline; it seems to be a default styling. In that case, maybe you can fix it using box shadows, which have more customizations available (cf this ring utility from Tailwind https://tailwindcss.com/docs/ring-width).

**Comment by goenning** [comment]
It turns out it was a breaking change on Tauri 2 that I did not notice.
TAURI_ENV_PLATFORM used to return `macos`, but it's now `darwin`, so that broke some of my CSS selectors that applied the ring utility. Will be fixed on next version coming out this week
