### ISSUE TITLE
Delete option not available in detail view of things under "Networking"

### ISSUE THREAD

**Issue by gk-fschubert** [aptakube/aptakube#340]
### Current and expected behavior

If an item can be deleted, the option should be available in the menu of a right-mouse-click as well as in the detailed view of the resource. 

![Kapture 2024-11-27 at 12 23 13](https://github.com/user-attachments/assets/93fd434a-cfff-457f-a4b4-8ae43a8778c0)

### Environment & Operating System

macOS sequoia

**Comment by goenning** [comment]
Good catch, I added it now on 1.9.1
