### ISSUE TITLE
Kubeconfig files not getting recognized on the aptakube app

### ISSUE THREAD

**Issue by Jassi-k8s** [aptakube/aptakube#341]
### Current and expected behavior

I have few kubeconf files, only one of them is recognized, while others are giving error:
![Screenshot 2024-11-27 165404](https://github.com/user-attachments/assets/fde9ba33-b5c5-4b57-97fb-f57e47ecfaf4)

### Environment & Operating System

Windows 11

**Comment by Jassi-k8s** [comment]
Please find snippets of the affected conf file. Its basically in .conf
format.

**Comment by goenning** [comment]
I don’t see anything attached, I think GitHub doesn’t support that. But you can email me at goenning@aptakube.com

thanks again!

**Comment by goenning** [comment]
This should be fixed now on 1.9.1, the app should be able to parse UTF-16 as well. But please reopen if it's not working. Thanks!

**Comment by Jassi-k8s** [comment]
Awesome, thanks!
