### ISSUE TITLE
kubernetes.io/role not parsed as Node Role

### ISSUE THREAD

**Issue by fernandocarletti** [aptakube/aptakube#35]
### Current and expected behavior

The value of `kubernetes.io/role` should be considered the node Role in the node view. Currently, it is completely ignored.

### Additional context

This is current considered by [Kubernetes itself](https://github.com/kubernetes/kubernetes/blob/ee8e76c6eaee46efc181eb8f70f1e9d710521281/pkg/printers/internalversion/printers.go#L1809-L1823).

### Operating System

macOS Ventura 13.1

### Environment

clientVersion:
  buildDate: "2022-12-08T19:51:43Z"
  compiler: gc
  gitCommit: b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d
  gitTreeState: clean
  gitVersion: v1.26.0
  goVersion: go1.19.4
  major: "1"
  minor: "26"
  platform: darwin/arm64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-10-25T19:38:29Z"
  compiler: gc
  gitCommit: 434bfd82814af038ad94d62ebe59b133fcb50506
  gitTreeState: clean
  gitVersion: v1.25.3
  goVersion: go1.19.2
  major: "1"
  minor: "25"
  platform: linux/arm64

**Comment by goenning** [comment]
Thanks! I'll get it fixed on the next version.

**Comment by goenning** [comment]
Fixed on 1.0, please reopen if the issue persists.
