### ISSUE TITLE
List in https://brew.sh

### ISSUE THREAD

**Issue by Hongbo-Miao** [aptakube/aptakube#36]
### What problem are you trying to solve?

(Thanks @goenning replying in the email 😃)

I initially thought I cannot use brew to install, because it does not list in the https://brew.sh/

However, `brew install --cask aptakube` does work.

I am not sure how, but it would be great to list in the https://brew.sh/ too!

**Comment by goenning** [comment]
Hey! 👋

That sounds like a good ideas, I'll do some research on how to do it.

In parallel, what I might do as well is update the aptakube.com home page to mention the homebrew command as an alternative installation method.

**Comment by goenning** [comment]
Seems like there is a known issue on homebrew, which is why the index is not being updated https://github.com/Homebrew/discussions/discussions/4000

Updated aptakube.com to include the command. Thanks for the suggestion!
