### ISSUE TITLE
Open Shell on pod doesn't work reliably on macos

### ISSUE THREAD

**Issue by jpallas** [aptakube/aptakube#37]
### Current and expected behavior

I'm seeing the Open Shell button send a kubectl command to an existing Terminal window instead of to a new one. The button should always open a new window and send the command to it.

On a somewhat related note, part of the command being executed on the pod is `sh -c "clear; echo -e <stuff>`.  But the pod's `sh` may not support the `-e` option on echo, resulting in a somewhat ugly display that starts with `-e clustername` instead of just `clustername`

### Operating System

macOS Monterery 12.6.2 on Intel MacBook Pro

### Environment

clientVersion:
  buildDate: "2022-06-15T14:17:29Z"
  compiler: gc
  gitCommit: 0f77da5bd4809927e15d1658fb4aa8f13ad890a5
  gitTreeState: clean
  gitVersion: v1.21.14
  goVersion: go1.16.15
  major: "1"
  minor: "21"
  platform: darwin/amd64
serverVersion:
  buildDate: "2022-08-17T09:22:54Z"
  compiler: gc
  gitCommit: 348bdc1040d273677ca07c0862de867332eeb3a1
  gitTreeState: clean
  gitVersion: v1.21.14-gke.4300
  goVersion: go1.16.15b7
  major: "1"
  minor: "21"
  platform: linux/amd64

**Comment by goenning** [comment]
Hey Joe, you're right, there is an issue with the apple terminal. I have a fix for it, which should be released with 1.0 in early January.

As for the second issue, do you have any example of a public image with that behaviour?

**Comment by jpallas** [comment]
> As for the second issue, do you have any example of a public image with that behaviour?

Yes, apparently images derived from debian use `dash`, and it [does not support `-e` on echo](https://manpages.debian.org/buster/dash/dash.1.en.html).  You can use 
```
docker run --rm debian sh -c 'echo -e example'
``` 
to see this in action.  (The image I am using is based on tomcat:8.5-jdk8-openjdk which is based on debian.)

**Comment by goenning** [comment]
But it seems the colored output is working regardless, I thought that it wouldn't when `-e` is not supported.

It's interesting that this one works: `docker run --rm debian sh -c '/bin/echo -e example'`

**Comment by goenning** [comment]
Fixed on 1.0, please reopen if the issue persists.
