### ISSUE TITLE
Support Helm

### ISSUE THREAD

**Issue by acemoo** [aptakube/aptakube#38]
### What problem are you trying to solve?

We'd like to be able to update our Helm-managed deployments.
This includes things like:
* Updating the image currently running
* Updating the horizontalPodAutoscaler settings
* Doing a rollback because the deployment is stuck

### Describe the solution you'd like

I've seen lens support this via both GUI and an embedded terminal that automatically assigns the kubeconfig context to match the currently selected k8s cluster and provides helm and kubectl. I'm happy with either way, the terminal might be a good idea to offer more flexibility to do things that aren't implemented in the GUI (yet).

**Comment by goenning** [comment]
Hey, I'm not too familiar with helmfile, but it seems to be something you'd store in git/s3 and then use the helmfile cli to apply it, I'm not sure how Aptakube would be able to managed that through the GUI. I want to add official support for Helm too, but that'd be to list/manage each individual release. I might need to research more about helmfile to see how we could fit it into Aptakube.

As for the suggestion of opening a terminal with the context pre-selected, that's definitely something we could add. As you mentioned, it can be useful for other scenarios too.

**Comment by acemoo** [comment]
I think Helmfile is a layer on top of Helm. Maybe Helmfile support directly doesn't make much sense as the file you'd be creating yourself isn't what ends up at Kubernetes.

Probably if Aptakube has Helm support that should let us do what we want. (if not I'll make a new feature request with more information) For now, I'm changing the Helmfile references to Helm in this issue.

**Comment by goenning** [comment]
Tentatively placing this on 1.3.0 release if all goes well 🤞

**Comment by OliverRC** [comment]
I'll throw my voice in for Helm integration. 
It's really the only reason I jump back to Lens from time to time is that I can view Helm releases

**Comment by joaocc** [comment]
Hi. Any updates on managing helm releases via aptakube? Without support for this, aptakube ends up not being used as a day-to-day tool, especially in places that use helm extensively. Thx

**Comment by goenning** [comment]
Hey @joaocc that's something I'm working on right now. The last version added the ability to list Helm Releases (read-only). 
What other operations do you perform frequently? I'm thinking of adding upgrade and downgrade, but I'm open for additional feedback too!

**Comment by joaocc** [comment]
Thx. in my case pretty much just inspect and delete, as we use gitops almost exclusively. But i'm pretty sure others will find upgrade useful.

**Comment by OliverRC** [comment]
Read-only is a great start; the actionable features I used most in Lens were Rollback or Downgrade, Upgrade, and Delete to remove the release. 

![image](https://github.com/aptakube/aptakube/assets/1888486/b350ea9e-2df7-4d9e-afd3-42fb9c185714)

**Comment by joaocc** [comment]
In the context of read-only operations, one thing that I find ultra-useful in Lens is to be able to toggle the ability see the parameters that were set explicitly (ie, diff to the values.yaml). Still read-only, but compacts info to what is most relevant.

**Comment by goenning** [comment]
I’m working on this right now @joaocc Thanks for the suggestion:)

I’m aiming for a release next week
