### ISSUE TITLE
Install using homebrew

### ISSUE THREAD

**Issue by metafeather** [aptakube/aptakube#4]
### What problem are you trying to solve?

I manage my machines primarily by using a text file list for homebrew.

### Describe the solution you'd like

I would like to be able to install Aptakube using homebrew on MacOS.

This would also work if later distributed via the App Store (via mas)

- https://github.com/Homebrew/homebrew-cask
- https://formulae.brew.sh/formula/mas

Thanks for your consideration.

**Comment by goenning** [comment]
Hey, great suggestion, I use homebrew a lot too. Never created a cask before, but doesn't look too complex. 

I'll try and get this done on the release going out this week.

**Comment by goenning** [comment]
```sh
➜  ~ brew install --cask aptakube
==> Downloading https://releases.aptakube.com/Aptakube_0.5.1_universal.dmg
Already downloaded: /Users/goenning/Library/Caches/Homebrew/downloads/7bd84db7a79d1f72017513bef1cfe55d807a5f3446a26ceeb61dc09afa3f5dd8--Aptakube_0.5.1_universal.dmg
==> Installing Cask aptakube
==> Moving App 'Aptakube.app' to '/Applications/Aptakube.app'
🍺  aptakube was successfully installed!
```

That was easier than I thought it would be, it's available on brew now!

**Comment by metafeather** [comment]
Fab, thanks! Works as advertised.
