### ISSUE TITLE
Doesn't work on no cluster

### ISSUE THREAD

**Issue by Udi-Hofesh** [aptakube/aptakube#40]
### Current and expected behavior

Aptakube is supposed to expose my K8s resources on its GUI, but it doesn't show anything at all. Kubectl doesn't show any issues and my app is running as normal.

### Operating System

macOS

### Environment

[Kubernetes v1.24.9](https://github.com/kubernetes/kubernetes/releases/tag/v1.24.9)

**Comment by goenning** [comment]
Hey Udi, that's an odd one. My best guess is that an error if being thrown and aptakube is not showing it. Can you help me with the following?

1. A screenshot of what you're seeing when you select Pods on the sidebar
2. `cat ~/Library/Logs/com.aptakube.Aptakube/Aptakube.log`
3. if you press `CMD+N` to get a list of namespaces, does it show any?

**Comment by Udi-Hofesh** [comment]
I uninstalled it and installed it again. Now it's working as expected. Actually faster than expected :) 
Not sure what solved the issue...I also played around with scaling replicas.

**Comment by goenning** [comment]
oh great, because I started to get worried this could be a big issue 😅

Hope you enjoy using the app, shout if you need anything!
