### ISSUE TITLE
Can't access resources

### ISSUE THREAD

**Issue by Sheldonwl** [aptakube/aptakube#42]
### Current and expected behavior

I can see all resources, but when I want to dive in deeper, I get an error, e.g.: This pod does not exist or may have been deleted. 

The expected behaviour is that I can go one level deeper into the resource, to then view, edit, shell into, etc. 

### Additional context

When looking at the serviceaccount@cluster, I see that the @ is replaced with %40, perhaps that is messing up things, but then I don't understand how I do have access to view the resources in the first place. 
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/6817520/212253633-b6e2db8b-7643-4e97-86cb-36fb7f9bc320.png">

### Operating System

MacOS 12.6
M1 Max 

### Environment

clientVersion:
  buildDate: "2022-08-17T18:54:23Z"
  compiler: gc
  gitCommit: 95ee5ab382d64cfe6c28967f36b53970b8374491
  gitTreeState: clean
  gitVersion: v1.24.4
  goVersion: go1.18.5
  major: "1"
  minor: "24"
  platform: darwin/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-07-13T14:19:57Z"
  compiler: gc
  gitCommit: c1de2d70269039fe55efb98e737d9a29f9155246
  gitTreeState: clean
  gitVersion: v1.23.9
  goVersion: go1.17.11
  major: "1"
  minor: "23"
  platform: linux/amd64

**Comment by Sheldonwl** [comment]
It does seem to work when I downgrade to version 0.9.2 (which btw is the latest version the brew installs), but when I download version 1.0.0, install the .dmg and use the same (unchanged) .kube/config file, it does not go one level deeper into the resource.

**Comment by goenning** [comment]
You're right. That's a bug, I'll get it fixed and release 1.0.1 as soon as possible.

As a temporary solution, you can rename your context to not have the @ character.

**Comment by goenning** [comment]
Hey Sheldon, this bug is fixed on 1.0.1, can you give it a try? The app will prompt for auto-update within 5 seconds after opening it.

**Comment by Sheldonwl** [comment]
Hi Guilherme, all good so far. Tested it on a few clusters and I can see all resources and can go one level deeper to get more details and edit the yaml. 👍  The prompt from the "old" app to install a newer version comes up, but when I want it to upgrade, nothing seems to happen, so I went to the website and downloaded the new .dmg. Brew also still only has 0.9.2, but those might be different bugs all together. This one has at least been fixed! Thanks! Love the tool so far! :)

**Comment by goenning** [comment]
I think you're missing a `brew update` to get the latest indexes, because 1.0.0 is the latest one on their website: https://formulae.brew.sh/cask/aptakube

the update to 1.0.1 is pending: https://github.com/Homebrew/homebrew-cask/pull/139659

**Comment by Sheldonwl** [comment]
You completely right, there was something wrong with my upstream repos, I can now indeed see it try to pull 1.0.0. Thanks!
