### ISSUE TITLE
Support for all built-in Access Control related resources

### ISSUE THREAD

**Issue by darth-vader-66** [aptakube/aptakube#43]
### What problem are you trying to solve?

I'd like to see an Access Control section in the sidebar, similar to Lens, so we can view things like Service Accounts, etc.

**Comment by goenning** [comment]
Hey Lord Vader, thanks for your suggestion. I prioritized all other resources first as they are a lot more popular, but RBAC related resources will be added for sure.

Mind if ask you how are you finding the current sidebar navigation with the current amount of built-in resources + CRD? Is it easy to navigate and find what you need?

**Comment by goenning** [comment]
This is now available on 1.1.0! It includes ServiceAccounts, Roles/ClusterRoles and Role/ClusterRole Bindings.

As mentioned on #49, in future releases we'll create the resource-specific view for these resources.
