### ISSUE TITLE
Support mouse back and forward clicks

### ISSUE THREAD

**Issue by Sheldonwl** [aptakube/aptakube#45]
### What problem are you trying to solve?

Don't know how hard this is to implement, but it would be nice to able to use the back and forward buttons on the mouse to move back or forward from the page you're on. Just like on your browser, or slack for example. This is now possible with the backspace button, so at a minimum it would be nice to use the back button on the mouse. (Perhaps this is something that needs to be mapped in the application software of the mouse)

### Describe the solution you'd like

When I use the back or forward buttons on my mouse, I would like the page to back or forward one step (or more if those steps are stored in memory).

**Comment by carlmontanari** [comment]
fyi, mentioned in #25

**Comment by Sheldonwl** [comment]
Can't believe I missed that, thanks @carlmontanari!

**Comment by goenning** [comment]
Yeah, we should be able to implement this on the app itself, but I need this feature to be available on Tauri first 😞

the workaround I use is the mouse software app, which you can map those mouse buttons to keyboard shortcuts. It’s not ideal, but it works pretty well!

**Comment by Sheldonwl** [comment]
That will definitely work fine for now, thanks!
