### ISSUE TITLE
Logs tab throws 'Unexpected error' 

### ISSUE THREAD

**Issue by Sheldonwl** [aptakube/aptakube#47]
### Current and expected behavior

When selecting any resource and selecting the 'Logs' tab, nothing is shown an a couple of errors are thrown. See pic: 
<img width="1753" alt="image" src="https://user-images.githubusercontent.com/6817520/212542427-4a0eefdb-03dc-4fdc-a63f-a3c9c51a7dc8.png">

### Additional context

Happens on every resource I've tried. 

### Operating System

MacOS 12.6

### Environment

clientVersion:
  buildDate: "2022-08-17T18:54:23Z"
  compiler: gc
  gitCommit: 95ee5ab382d64cfe6c28967f36b53970b8374491
  gitTreeState: clean
  gitVersion: v1.24.4
  goVersion: go1.18.5
  major: "1"
  minor: "24"
  platform: darwin/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-07-13T14:19:57Z"
  compiler: gc
  gitCommit: c1de2d70269039fe55efb98e737d9a29f9155246
  gitTreeState: clean
  gitVersion: v1.23.9
  goVersion: go1.17.11
  major: "1"
  minor: "23"
  platform: linux/amd64

**Comment by goenning** [comment]
Dang, this is looking like another issue related to @ on the context name. I went through a few features during testing and I missed the logs 😣

Can you confirm if Pod/Node Shell access is working?

---

Thanks for reporting these bugs by the way. I'm sorry you're having a bad experience with the app. Send me a message through the in-app feedback button (context selector view) and I can get your trial extended.

**Comment by Sheldonwl** [comment]
Shell access seems to be working just fine 👍

**Comment by goenning** [comment]
hey @Sheldonwl this is fixed now on 1.0.2, please give it a go! Reopen if the issue persists, but I think that's the last one related to special chars on context names 🤞

Brew update is pending approval: https://github.com/Homebrew/homebrew-cask/pull/139710

**Comment by Sheldonwl** [comment]
Hi @goenning, I've checked and it's indeed fixed. Thanks! 👍
