### ISSUE TITLE
Read kubeconfig and port forward over SSH

### ISSUE THREAD

**Issue by metafeather** [aptakube/aptakube#5]
### What problem are you trying to solve?

Many of my working environments are on remote instances and Pods (e.g. behind a vpn or inside cluster) and have no UI.

Currently I use k9s to provide a terminal UI to clusters using local kubeconfig:

- https://github.com/derailed/k9s

### Describe the solution you'd like

I would like to be able to load a remote kubeconfig file via an SSH connection and automatically port forward to the remote accessible API so as to use Aptakube as my UI to the cluster.

Thanks for you consideration.

**Comment by goenning** [comment]
Hey, thanks for the suggestion.

I'm not sure I completely understood your setup. Can you share more info about and how do you use kubectl/k9s currently?

Does your local kubeconfig point to your SSH tunnel address?

**Comment by metafeather** [comment]
I was using k9s on the remote Pod itself - thanks to your comment I realised I could copy the .kubeconfig locally and change the `cluster.server` property to point to the local SSH port-forwarded tunnel to the remote k8s cluster API and Aptakube will work just fine 👍
