### ISSUE TITLE
Log panel loading indefinitely 

### ISSUE THREAD

**Issue by julienFlowdesk** [aptakube/aptakube#50]
### Current and expected behavior

When clicking on a pod and on the "Logs" Panel, I should be able to see my logs updated in real-time with the Tail option.

### Additional context

Aptakube stays in "Waiting for logs..." state.
Then errors the following message : 
# cat ~/Library/Logs/com.aptakube.Aptakube/Aptakube.log
[2023-01-23][08:22:26][aptakube::k8s::log_stream][WARN] log stream error: HyperError: error reading a body from connection: error reading a body from connection: timed out

Sometime (random) I am able to see some line of logs which seems to be stuck.

I am well connected to my context, have the network access and can do kubectl logs on the pods without issues.

### Operating System

macOS

### Environment

clientVersion:
  buildDate: "2022-12-08T19:51:43Z"
  compiler: gc
  gitCommit: b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d
  gitTreeState: clean
  gitVersion: v1.26.0
  goVersion: go1.19.4
  major: "1"
  minor: "26"
  platform: darwin/arm64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-10-26T09:25:34Z"
  compiler: gc
  gitCommit: e35c4457f66187eff006dda6d2c0fe12144ef2ec
  gitTreeState: clean
  gitVersion: v1.24.7-gke.900
  goVersion: go1.18.7b7
  major: "1"
  minor: "24"
  platform: linux/amd64

**Comment by goenning** [comment]
1. If you change from Tail to a few days ago, does it show something?

2. Are you able to reproduce this constantly or is it intermittent?

The "connection timeout" error should be retried shortly after failures, but I'll do some more testing here to confirm.

**Comment by julienFlowdesk** [comment]
Hello @goenning,

Sorry for the issue which is in fact entirely my fault (I was expecting to see the last logs in the Tail view like the kubectl tail, even though those were from hours ago but the Live Tail view starts to listen logs when started)
Bottom line, Aptakube is working as expected, amazing product by the way !

Cheers,

**Comment by goenning** [comment]
Great, thanks for the update. You're actually the second to mention this "issue", which makes me think I need to improve the UX a bit. Either by showing the last log as kubectl does, or maybe a "Connecting -> Connected" alongside the "Waiting for new logs", to at least show we are connected, but there's no logs yet.
