### ISSUE TITLE
Make node names clickable everywhere

### ISSUE THREAD

**Issue by stormsilver** [aptakube/aptakube#52]
### What problem are you trying to solve?

When I'm viewing a deployment, I can see all the pods and which nodes they are on. Sweet!

Except when I want to look at that node to see what else is on it, I have to copy the node name, navigate to nodes, and find it. Bitter.

### Describe the solution you'd like

This is a request to make the node name clickable. Particularly on the deployments page, but really _anywhere there's a node name_.

**Comment by goenning** [comment]
Fixed on 1.2.0
