### ISSUE TITLE
Multi item selection

### ISSUE THREAD

**Issue by carlmontanari** [aptakube/aptakube#55]
### What problem are you trying to solve?

it would be cool to be able to select multiple rows of items at once for bulk deletion stuff. maybe this is already possible and I missed it?

### Describe the solution you'd like

shift click or just drag and highlight of multiple rows at one time would be great. then right-click context menu could show just "delete" (instead of the current "delete" and "yaml"). not sure how easy/hard that would be with tauri -- hopefully easy :D

**Comment by spr-mweber3** [comment]
I second that. Would make it much more easy.

**Comment by nicholas-ochoa** [comment]
Hoping the multi-select functionality will extend to the namespace dropdown at the top right of the window:

<img width="482" alt="image" src="https://github.com/aptakube/aptakube/assets/126299/aeba6cf3-428f-4498-bd21-676932199e12">

Ideally, it would be great if there was a checkbox to select multiple namespaces after filtering down the results.

**Comment by goenning** [comment]
I'm working on this feature at the moment, and I currently have a beta version of it.

If you're on a macOS and want to try it early, you can download it here:

https://releases.aptakube.com/Aptakube_1.7.0-beta1_universal.dmg

Please let me know if you have any feedback, or find any bugs :)

**Comment by goenning** [comment]
This is available on 1.7.0 now 🚀
