### ISSUE TITLE
aptakube can't read kubeconfig.

### ISSUE THREAD

**Issue by anarcher** [aptakube/aptakube#56]
### Current and expected behavior

```
[2023-01-30][06:35:28][aptakube::k8s::context][ERROR] Error reading kubeconfig: the structure of the parsed kubeconfig is invalid: invalid type: unit value, expected a sequence
```

k9s and kubectl works well.

How do I start to debug for it?

thanks :-)

### Operating System

macos 13.1

### Environment

```
$ k version --output=yaml
clientVersion:
  buildDate: "2022-10-12T10:47:25Z"
  compiler: gc
  gitCommit: 434bfd82814af038ad94d62ebe59b133fcb50506
  gitTreeState: clean
  gitVersion: v1.25.3
  goVersion: go1.19.2
  major: "1"
  minor: "25"
  platform: darwin/arm64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-11-29T18:45:03Z"
  compiler: gc
  gitCommit: abb98ec0631dfe573ec5eae40dc48fd8f2017424
  gitTreeState: clean
  gitVersion: v1.24.8-eks-ffeb93d
  goVersion: go1.18.8
  major: "1"
  minor: 24+
  platform: linux/amd64

```

**Comment by goenning** [comment]
Hey @anarcher 

Do you have all your configs in a single or multiple kubeconfig files?

We use a Rust based parser in Aptakube that is a bit more strict than Go. The error indicates one of the properties is empty/missing, but an array was expected.

Would you be able to obfuscate any sensitive information and share your kubeconfig files with me? Either on this thread or via email goenning@aptakube.com

I'd love to get to the bottom of this issue and relax this validation to match what they do on kubectl.

Thanks!

**Comment by anarcher** [comment]
@goenning thanks for kind reply.

I use multiple kubeconfig files. (`APTAKUBECONFIG=/Users/anarcher/.kube/config:/Users/anarcher/.kube/dev-kubeconfig
:...`)   One kubeconfig file (first kubeconfig in KUBECONFIG) `~/.kube/config`  looks like below:

```
apiVersion: v1
clusters: null
contexts: null
current-context:  dev1
kind: Config
preferences: {}
users: null
```
When I remove all contents of this config, aptakube loads kubeconfig well. :-)

IMHO, If this config is a problem, aptakube parser can handle to ignore well. :-)
I will close this issue

thanks!

**Comment by goenning** [comment]
Yeah, I'm working on making Aptakube a little less strict with configs 😊

Thanks for the update!
