### ISSUE TITLE
When I open aptakube in terminal,  it seems to not read KUBECONFIG env. 

### ISSUE THREAD

**Issue by anarcher** [aptakube/aptakube#58]
### Current and expected behavior

Because of aws-auth things, I open aptakube in terminal to use `/Applications/Aptakube.app/Contents/MacOS/Aptakube
`. 
- Like `code` command in VSCode,  I would like to use `aptakube` cli command.
- When I open aptakube in terminal, It seems to not read `$KUBECONFIG` or `$APTAKUBECONFIG`.

```
export APTAKUBECONFIG=~/.kube/another-config
/Applications/Aptakube.app/Contents/MacOS/Aptakube
```

Kube contexts is not changed.

Thanks

### Environment & Operating System

macos

**Comment by goenning** [comment]
Hi @anarcher 

Can you try this?

```
APTAKUBECONFIG=~/.kube/another-config open /Applications/Aptakube.app
```

That's what I use. It should be possible to make a shortcut like VSCode as well so you don't have to type all that, I'll try it again when I'm on my laptop and will let you know.

**Comment by goenning** [comment]
finally got some time to try this. Basically what you need to do is:

add this to your .zshrc or .bashrc
```
alias aptakube=/Applications/Aptakube.app/Contents/MacOS/Aptakube
```

then you should be able to do simplify the command above to `APTAKUBECONFIG=~/.kube/another-config aptakube`

Hope that helps!

**Comment by anarcher** [comment]
Thanks!  :-)
