### ISSUE TITLE
Truncated Events Message

### ISSUE THREAD

**Issue by bryan-lott** [aptakube/aptakube#65]
### Current and expected behavior

Currently the Message portion of Events is truncated, without any obvious way to expand it, ex:
![image](https://user-images.githubusercontent.com/4428312/217589253-5a0b379c-83e6-46f7-b3aa-0427d62c03fa.png)

Would appreciate a way to either expand the message, wrap it to multiple lines, or click into it and see the full message. Even a hover with the full message would be okay, though that would prevent copy/paste from working.

### Environment & Operating System

macOs Monterey v12.5.1

**Comment by goenning** [comment]
Yeah, that doesn't look great. Is it just the message column that is a problem? Can you read the other values if you resize the column?

**Comment by bryan-lott** [comment]
I've resized it as much as I'm able to (there seems to be a hard limit) and it's not always enough to get the full message.

**Comment by goenning** [comment]
Thanks for reporting this issue.

I'm changing this on the next version (ETA tomorrow)

![image](https://user-images.githubusercontent.com/94755/217795579-5202f68b-3b18-4afc-a22a-10dae96b2fad.png)

**Comment by goenning** [comment]
Update: It's live now 😊

https://github.com/aptakube/aptakube/releases/tag/1.2.0

Please reopen if the issue persists.

**Comment by bryan-lott** [comment]
Looks fantastic, thanks so much and really appreciate the fast turnaround!
