### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by molszews** [aptakube/aptakube#66]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Hey, I'm big fan of this product (MacOS version), but I have to visit main page just to check for updates and then install (actually overwrite) it manually - any chance for auto-update mechanism?

**Comment by goenning** [comment]
Hey, the app already has an auto-update feature. What OS are you using?

**Comment by goenning** [comment]
Quick video to show how it should work

https://user-images.githubusercontent.com/94755/218250786-6aa17dbc-5173-4db8-abbc-6b31ae6a57c5.mp4

**Comment by molszews** [comment]
Indeed, it worked now! I'm not sure what version I had before, but with v1.1.0 I got the popup as in attached recording
