### ISSUE TITLE
Add support for proxy-url kubeconfig option

### ISSUE THREAD

**Issue by nint8835** [aptakube/aptakube#69]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

In the kubeconfig, you can define a proxy to use to connect to the cluster via the `proxy-url` field on the `cluster` object (see docs [here](https://pkg.go.dev/k8s.io/client-go/tools/clientcmd/api#Cluster)).

Aptakube should support using this field to configure the proxy settings to connect to the cluster, so clusters requiring this can be connected to with Aptakube.

**Comment by goenning** [comment]
Released on 1.2.1 🚀 Thanks for helping me test it! 

![](https://media4.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif?cid=ecf05e47r2im1fts8ng7kgsh5kxc0vrpwg4i6pan6snfm3rf&rid=giphy.gif&ct=g)
