### ISSUE TITLE
Search bar in the cluster selection

### ISSUE THREAD

**Issue by metmin** [aptakube/aptakube#7]
### What problem are you trying to solve?

Greetings, I am working with almost 300 clusters in a single kubeconfig file and I am having trouble finding the cluster i want. 

### Describe the solution you'd like

Having a search bar helps me a lot to find the machine I'm looking for.
Also, if we create groups and register the clusters in these groups, we can find the cluster group we are looking for more easily.

**Comment by goenning** [comment]
hey @metmin, thanks for your suggestion.

The next version (0.7.0) will have a search bar on the context selector view as a short term solution. On the subsequent release (0.8.0), I'll add a few extra things such as: favorites, groups/sets as you suggested, recently used contexts, assign an alias/icon to make it usable with hundreds of clusters/contexts
