### ISSUE TITLE
Remember sort preference

### ISSUE THREAD

**Issue by molszews** [aptakube/aptakube#71]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

I often navigate through many sections, navigating using back-next icons seems to preserve my sort preferences, but if I navigate through sections like Pods -> Deployments -> Pods I often need to adjust them (e.g. to sort by Age). Any chance to keep sort settings at least until app gets restarted?

**Comment by aexvir** [comment]
+1 to this, the default columns view has limited usefulness for me, so I'd rather chose the columns I want to be displayed and the order

**Comment by goenning** [comment]
This is now live on 1.3.0 🎉
