### ISSUE TITLE
Consider tabs in navigation history

### ISSUE THREAD

**Issue by fernandocarletti** [aptakube/aptakube#72]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

When moving back and forth using the keyboard shortcuts (`cmd+[` and `cmd+]`) the history does not consider the tabs in the workload view. This can be reproduced by:

1. Go to `Workloads` -> `Deployments`;
2. Open any `Deployment`; 
3. Switch to the `Logs` tab;
4. Go back in history (press `cmd+[`).

You will get back to the Deployments list instead of the Deployment details.

**Comment by goenning** [comment]
Shipped on 1.5
