### ISSUE TITLE
Copy-to-clipboard button for names

### ISSUE THREAD

**Issue by kosta** [aptakube/aptakube#73]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

I need to copy/paste names from aptakube to terminal, slack, etc. A button here would be nice:

![image](https://user-images.githubusercontent.com/104116/220553019-572fb241-8de9-409a-bcfd-cfce88cc890f.png)

**Comment by kosta** [comment]
Would also be nice for secret values

**Comment by goenning** [comment]
👍 I'll try fit into 1.3.0 release

**Comment by goenning** [comment]
Added to object names and ConfigMap/Secrets

https://user-images.githubusercontent.com/94755/223130130-fc45b246-cb41-4706-96c8-2d1f183f6bb6.mp4

**Comment by goenning** [comment]
This is now live on 1.3.0 🎉 Thanks for the suggestion @kosta
