### ISSUE TITLE
Ability to copy texts from logs

### ISSUE THREAD

**Issue by thearchitectxy** [aptakube/aptakube#74]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Ability to copy texts from logs

**Comment by goenning** [comment]
Hey @thearchitectxy, that's already possible, unless there was a regression.

What OS are you using?

**Comment by thearchitectxy** [comment]
Hi  @goenning  Mac Os on M1 mac cant do CMD + c not right click
<img width="1551" alt="Screen Shot 2023-02-23 at 8 35 14 PM" src="https://user-images.githubusercontent.com/84636940/220971024-44326d1c-cdc4-4220-81c1-d2946ce80902.png">

**Comment by goenning** [comment]
That's odd, I'm on Mac M1 too and it works fine. Right click won't work, that's correct, it wasn't implemented. but CMD+C should work. 

Can you try:

1. Select some other text like the pod name and try copy that?
2. Select the logs and use the menu bar Edit -> Copy

Does any of that work?

**Comment by thearchitectxy** [comment]
> That's odd, I'm on Mac M1 too and it works fine. Right click won't work, that's correct, it wasn't implemented. but CMD+C should work.
> 
> Can you try:
> 
> 1. Select some other text like the pod name and try copy that?
> 2. Select the logs and use the menu bar Edit -> Copy
> 
> Does any of that work?

Using Edit menu and copy works for me thanks
