### ISSUE TITLE
Improve breadcrumbs usability

### ISSUE THREAD

**Issue by netcelli-tux** [aptakube/aptakube#76]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Breadcrumbs that are located above the tile are clickable but they are missing hover state. Like other UI elements I would expect them to have underline or background style when I hover over a link.

Also breadcrumbs are usually separated by symbols like ">" or "/" to state their hierarchical structure.

**Comment by goenning** [comment]
It was actually never meant to be an actual breadcrumbs, which is why it also only goes one level deep and it wasn't clickable until a release or two ago. I'll add the hover state to make it more apparent. Are you using that often?

**Comment by netcelli-tux** [comment]
> It was actually never meant to be an actual breadcrumbs, which is why it also only goes one level deep and it wasn't clickable until a release or two ago. I'll add the hover state to make it more apparent. Are you using that often?

I mainly use back action or I click on the left sidebar menu. So I don't really use them. I just noticed they were missing hover state.

**Comment by goenning** [comment]
This is now live on 1.3.0 🎉
