### ISSUE TITLE
make the left sidebar so you can resize it.

### ISSUE THREAD

**Issue by jaroet** [aptakube/aptakube#8]
### What problem are you trying to solve?

We have somewhat longer context names in kube so as well as the first screen where you select the contexts as in the following screens we cannot see the context we are in. 

### Describe the solution you'd like

Would be great if the left sidebar would be resizable too.

**Comment by goenning** [comment]
hey @jaroet thanks for your suggestion. This will be available on the next release :)

https://user-images.githubusercontent.com/94755/197899483-dad16312-3a77-4acd-befa-b3e7f213691f.mp4

**Comment by goenning** [comment]
Thanks again for the suggestion! This was released in 0.7.0. Keep an eye on the next release, there will be a few more improvements around this area, especially for folks with hundreds of contexts and/or contexts with long names.
