### ISSUE TITLE
Logs strangely formatted

### ISSUE THREAD

**Issue by SWojtyla** [aptakube/aptakube#80]
### Current and expected behavior

When viewing my logs, they are really hard to read because the text is displayed in a not very user friendly way with lots of spaces

![image](https://user-images.githubusercontent.com/36441058/223365501-ba0b5549-8413-4154-9d4f-9226c43579c6.png)

Compared to (Open)Lens 
![image](https://user-images.githubusercontent.com/36441058/223365804-085111ba-c973-4b85-80ae-e08cabd565a1.png)

### Environment & Operating System

OS : Windows 11
kubectl version :
- Client Version: v1.26.2
- Kustomize Version: v4.5.7
- Server Version: v1.24.3

**Comment by goenning** [comment]
Hey! I'm trying to reproduce this but I'm unable to so far. 

Would you mind going to back to version 1.1.0 or 1.0.0 to see if that's happening there as well? That'd help me a lot! Downloads are available here https://github.com/aptakube/aptakube/releases

**Comment by SWojtyla** [comment]
Hey, first of all thx for the quick reply !
On the v1.1.0 I get following: 
 
![image](https://user-images.githubusercontent.com/36441058/223393199-3df0df2e-b782-43cf-a8c6-e5ef2b3548e5.png)

I don't know if this means something/is related to or not but when I choose "logs from Tail" it looks fine actually
![image](https://user-images.githubusercontent.com/36441058/223393729-95c519ad-2099-42d6-8a22-df15489006aa.png)

**Comment by goenning** [comment]
Thanks @SWojtyla that was actually very helpful.

Would you like to test a potential fix? I wasn't able to reproduce, but I'm fairly sure this is fixed now. It's a beta release, you can download from https://releases.aptakube.com/Aptakube_1.3.0-beta3_x64_en-US.msi

Give it a try and let me know how it goes, hopefully it'll be much better than before 🤞
