### ISSUE TITLE
Add more columns to node list, such as kubelet, kubeproxy, OS Image / Kernel

### ISSUE THREAD

**Issue by spole-plcom** [aptakube/aptakube#84]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

On the nodes view -- can you include the node version in the view.

**Comment by fernandocarletti** [comment]
It is in the `.status.nodeInfo.kubeletVersion` field. That's actually info I had to use kubectl to quickly get it a few days ago while updating a cluster.

**Comment by goenning** [comment]
Ah, ok. That field is available here, but I guess you'd like to see this on the table view? 

![image](https://user-images.githubusercontent.com/94755/224088627-76b7b1a5-b949-44e9-9b2c-6c1dccd391b6.png)

**Comment by fernandocarletti** [comment]
I believe this is related: https://github.com/aptakube/aptakube/issues/34, since the ability to set custom columns would also solve this issue.

**Comment by goenning** [comment]
Yes, but It might be beneficial to add this column (at least kubelet ?!) until #34 is implemented as that one requires a lot more work

**Comment by fernandocarletti** [comment]
Indeed. I was just adding it here to keep the reference for the future since it sounds like a related task.
