### ISSUE TITLE
Custom Image/Alias for Contexts

### ISSUE THREAD

**Issue by darth-vader-66** [aptakube/aptakube#85]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

I'd like to be able to set an alias for my contexts, e.g., dev, staging, etc. Right now, I have the long string from EKS and the meaningful part is on the tail end that gets cut off. Another idea would be the ability to add an image for a context, like a profile picture of sorts (Lens does that). I found it very useful so I don't get confused which cluster I am working on.

**Comment by goenning** [comment]
Custom icons are supported using extensions in kubeconfig, some docs here: https://aptakube.com/docs/context-extension

As for alias, I recommend renaming the context (not cluster/user) which means the name remains consistent across all kubernetes tools, and also makes usage of kubectl much easier when dealing with multiple clusters.
