### ISSUE TITLE
Create a port-forward from services and pods view

### ISSUE THREAD

**Issue by fernandocarletti** [aptakube/aptakube#89]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Sometimes for debugging purposes, setting a port-forward for pods and services is quite helpful. Having this feature in Aptakube would be great.

**Comment by goenning** [comment]
Seems to be a duplicate of https://github.com/aptakube/aptakube/issues/22 please upvote that one as well :)

**Comment by fernandocarletti** [comment]
Done. I searched for `port-forward`, found nothing and created it :P
