### ISSUE TITLE
Select columns to display

### ISSUE THREAD

**Issue by MattKetmo** [aptakube/aptakube#92]
### What problem are you trying to solve? Do you a suggestion on how to solve it?

It would be nice to be able to hide some columns when listing resources, in order to save some horizontal spaces.

I imagine having a select box, at the right of the Filter input, which would list all columns displayed.
Those columns would be selected by default, and we would be able to deselect the ones that we don't want to display, or vice versa.

![CleanShot 2023-04-11 at 09 40 14](https://user-images.githubusercontent.com/334996/231091169-fc21f86e-e954-419e-8879-92c9912e8bb8.png)

My main use case: the last column "Age" is one that I often use. But it's always hidden on the right so I have to scroll horizontally to see it. I would love removing unnecessary columns for my needs (eg. Node, Pod IP).

PS1: ability to reorder columns via drag & drop would also be a nice to have.
PS2: could be also very useful with Custom Columns https://github.com/aptakube/aptakube/issues/34

**Comment by goenning** [comment]
Done in 1.7.11

sorry for keeping you waiting this long 😅
