### ISSUE TITLE
Getting connection error sometimes

### ISSUE THREAD

**Issue by raman-mt** [aptakube/aptakube#98]
### Current and expected behavior

<img width="863" alt="Screenshot 2023-04-22 at 13 07 20" src="https://user-images.githubusercontent.com/73097634/233777625-bedbc871-e1c5-4f88-a1a4-3dd873b0d4c4.png">

Getting this error sometimes when i use the Aptakube app even though everything seems to be working fine when trying to use kubectl. 

### Environment & Operating System

macOS
EKS 1.22

**Comment by goenning** [comment]
How often do you get this? I suppose it's intermittent and when you move to another resource and come back it works?
