### ISSUE TITLE
No HorzonalPodAutoscalers

### ISSUE THREAD

**Issue by raman-mt** [aptakube/aptakube#99]
### Current and expected behavior

<img width="1691" alt="Screenshot 2023-04-22 at 13 17 39" src="https://user-images.githubusercontent.com/73097634/233778042-883ce5c1-516b-47b1-825f-030449c91e40.png">

App shows no HorizontalPodAutoscalers even though there are many

### Environment & Operating System

MacOS Ventura
EKS 1.22

**Comment by goenning** [comment]
Could it be because we only support HPA v2? What version of the HPA are tou using?

**Comment by goenning** [comment]
Closing this for now, doesn't seem actionable right now. Double check what version of HPA you're using and if you're looking at the correct namespace.
